//! Client-owned schema export boundary.
//!
//! This module defines which client-owned DTOs are allowed to become schema
//! documents. Public DTOs in this manifest derive `JsonSchema` and are exported
//! as deterministic schema files for shell integration.

pub use crate::contracts::export::{
    ClientContractDomain, ClientContractKind, ClientContractStability, ClientContractType,
    ClientSchemaInternalExclusion, client_contract_types, client_schema_internal_exclusions,
};

#[cfg(any(feature = "schema", test))]
use schemars::{Schema, schema_for};
#[cfg(any(feature = "schema", test))]
use std::{fs, path::Path};

#[cfg(any(feature = "schema", test))]
pub struct SchemaDocument {
    pub file_name: &'static str,
    pub schema: Schema,
}

#[cfg(any(feature = "schema", test))]
macro_rules! schema_doc {
    ($file_name:literal, $ty:ty) => {
        SchemaDocument {
            file_name: $file_name,
            schema: schema_for!($ty),
        }
    };
}

pub fn public_client_schema_contracts() -> Vec<ClientContractType> {
    client_contract_types()
}

pub fn internal_client_schema_exclusions() -> Vec<ClientSchemaInternalExclusion> {
    client_schema_internal_exclusions()
}

#[cfg(any(feature = "schema", test))]
pub fn client_schema_documents() -> Vec<SchemaDocument> {
    let mut documents = vec![
        schema_doc!(
            "gateway_settings_store.json",
            crate::gateway::settings_store::GatewaySettingsStore
        ),
        schema_doc!(
            "identity_authorization_publication.json",
            crate::gateway::identity_authorization::IdentityAuthorizationPublication
        ),
        schema_doc!(
            "gateway_session_publication.json",
            crate::gateway::session_controller::GatewaySessionPublication
        ),
        schema_doc!("client_scope.json", crate::core::ClientScope),
        schema_doc!("client_revisions.json", crate::core::ClientRevisions),
        schema_doc!("client_generation.json", crate::core::ClientGeneration),
        schema_doc!(
            "client_request_state.json",
            crate::request_state::RequestState<serde_json::Value>
        ),
        schema_doc!(
            "client_request_failure.json",
            crate::request_state::ClientRequestFailure
        ),
        schema_doc!(
            "request_update_outcome.json",
            crate::request_state::RequestUpdateOutcome
        ),
        schema_doc!("client_intent.json", crate::core::ClientIntent),
        schema_doc!("client_effect_plan.json", crate::core::ClientEffectPlan),
        schema_doc!(
            "client_effect_completion.json",
            crate::core::ClientEffectCompletion
        ),
        schema_doc!(
            "client_effect_cancellation.json",
            crate::core::ClientEffectCancellation
        ),
        schema_doc!("client_identity.json", crate::ids::ClientIdentity),
        schema_doc!(
            "client_identity_namespace.json",
            crate::ids::ClientIdentityNamespace
        ),
        schema_doc!("client_feature.json", crate::ids::ClientFeature),
        schema_doc!(
            "client_domain_identity.json",
            crate::ids::ClientDomainIdentity
        ),
        schema_doc!(
            "active_thread_phase_snapshot.json",
            crate::state::snapshot::ActiveThreadPhaseSnapshot
        ),
        schema_doc!(
            "active_thread_snapshot.json",
            crate::state::snapshot::ActiveThreadSnapshot
        ),
        schema_doc!(
            "active_thread_status_snapshot.json",
            crate::state::snapshot::ActiveThreadStatusSnapshot
        ),
        schema_doc!(
            "artifact_action_status.json",
            crate::artifacts::actions::ArtifactActionStatus
        ),
        schema_doc!(
            "artifact_http_download_request_plan_error.json",
            crate::artifacts::actions::ArtifactHttpDownloadRequestPlanError
        ),
        schema_doc!(
            "artifact_http_download_error.json",
            crate::artifacts::http_download::ArtifactHttpDownloadError
        ),
        schema_doc!(
            "artifact_http_download_progress.json",
            crate::artifacts::http_download::ArtifactHttpDownloadProgress
        ),
        schema_doc!(
            "artifact_http_download_request.json",
            crate::artifacts::http_download::ArtifactHttpDownloadRequest
        ),
        schema_doc!(
            "artifact_http_download_result.json",
            crate::artifacts::http_download::ArtifactHttpDownloadResult
        ),
        schema_doc!(
            "artifact_file_action_block_reason.json",
            crate::artifacts::actions::ArtifactFileActionBlockReason
        ),
        schema_doc!(
            "artifact_binding_target_kind.json",
            crate::artifacts::presentation::ArtifactBindingTargetKind
        ),
        schema_doc!(
            "artifact_binding_target_part.json",
            crate::artifacts::presentation::ArtifactBindingTargetPart
        ),
        schema_doc!(
            "artifact_presentation_policy.json",
            crate::artifacts::presentation::ArtifactPresentationPolicy
        ),
        schema_doc!(
            "artifact_presentation_block_reason.json",
            crate::artifacts::presentation::ArtifactPresentationBlockReason
        ),
        schema_doc!(
            "execution_draft_selection.json",
            crate::composer::reconciliation::ExecutionDraftSelection
        ),
        schema_doc!(
            "execution_draft_reconciliation.json",
            crate::composer::reconciliation::ExecutionDraftReconciliation
        ),
        schema_doc!(
            "execution_draft_reconciliation_reason.json",
            crate::composer::reconciliation::ExecutionDraftReconciliationReason
        ),
        schema_doc!(
            "artifact_upload_file_request.json",
            crate::artifacts::upload::ArtifactUploadFileRequest
        ),
        schema_doc!(
            "artifact_version_key.json",
            crate::artifacts::actions::ArtifactVersionKey
        ),
        schema_doc!(
            "capability_rejection_row.json",
            crate::timeline::labels::CapabilityRejectionRow
        ),
        schema_doc!(
            "client_effect.json",
            crate::notifications::effects::ClientEffect
        ),
        schema_doc!(
            "client_snapshot.json",
            crate::state::snapshot::ClientSnapshot
        ),
        schema_doc!(
            "client_security_diagnostic.json",
            crate::security::ClientSecurityDiagnostic
        ),
        schema_doc!(
            "client_security_diagnostic_row.json",
            crate::security::ClientSecurityDiagnosticRow
        ),
        schema_doc!(
            "client_security_enforcement_status.json",
            crate::security::ClientSecurityEnforcementStatus
        ),
        schema_doc!(
            "client_security_filesystem_access.json",
            crate::security::ClientSecurityFilesystemAccess
        ),
        schema_doc!(
            "client_turn_security_summary.json",
            crate::security::ClientTurnSecuritySummary
        ),
        schema_doc!(
            "composer_attachment.json",
            crate::composer::attachments::ComposerAttachment
        ),
        schema_doc!(
            "composer_attachment_kind.json",
            crate::composer::attachments::ComposerAttachmentKind
        ),
        schema_doc!(
            "composer_attachment_upload_state.json",
            crate::composer::attachments::ComposerAttachmentUploadState
        ),
        schema_doc!(
            "composer_capability.json",
            crate::composer::capabilities::ComposerCapability
        ),
        schema_doc!(
            "composer_capability_kind.json",
            crate::composer::capabilities::ComposerCapabilityKind
        ),
        schema_doc!(
            "composer_capability_target.json",
            crate::composer::capabilities::ComposerCapabilityTarget
        ),
        schema_doc!(
            "composer_capability_menu_visibility.json",
            crate::composer::capabilities::ComposerCapabilityMenuVisibility
        ),
        schema_doc!(
            "composer_capability_presentation.json",
            crate::composer::capabilities::ComposerCapabilityPresentation
        ),
        schema_doc!(
            "composer_submission_plan.json",
            crate::composer::capabilities::ComposerSubmissionPlan
        ),
        schema_doc!(
            "composer_domain_state.json",
            crate::composer::state_machine::ComposerDomainState
        ),
        schema_doc!(
            "composer_domain_action.json",
            crate::composer::state_machine::ComposerDomainAction
        ),
        schema_doc!(
            "composer_domain_transition.json",
            crate::composer::state_machine::ComposerDomainTransition
        ),
        schema_doc!(
            "composer_reply_target.json",
            crate::composer::state_machine::ComposerReplyTarget
        ),
        schema_doc!(
            "composer_mention_candidate.json",
            crate::composer::state_machine::ComposerMentionCandidate
        ),
        schema_doc!(
            "composer_mention_selection.json",
            crate::composer::state_machine::ComposerMentionSelection
        ),
        schema_doc!(
            "composer_draft.json",
            crate::composer::draft::ComposerDraft<
                crate::composer::attachments::ComposerAttachment,
                crate::composer::capabilities::ComposerCapability,
            >
        ),
        schema_doc!(
            "composer_domain_draft.json",
            crate::composer::draft::ComposerDomainDraft
        ),
        schema_doc!(
            "composer_draft_lifecycle_state.json",
            crate::composer::draft::ComposerDraftLifecycleState
        ),
        schema_doc!(
            "composer_draft_lifecycle_action.json",
            crate::composer::draft::ComposerDraftLifecycleAction
        ),
        schema_doc!(
            "composer_draft_lifecycle_transition.json",
            crate::composer::draft::ComposerDraftLifecycleTransition
        ),
        schema_doc!(
            "composer_permission_mode_option.json",
            crate::composer::permissions::ComposerPermissionModeOption
        ),
        schema_doc!(
            "composer_model_selection.json",
            crate::composer::model_selection::ComposerModelSelection
        ),
        schema_doc!(
            "composer_model_selection_state.json",
            crate::composer::model_selection::ComposerModelSelectionState
        ),
        schema_doc!(
            "composer_model_selection_candidate.json",
            crate::composer::model_selection::ComposerModelSelectionCandidate
        ),
        schema_doc!(
            "provider_model_display_key.json",
            crate::providers::presentation::ProviderModelDisplayKey
        ),
        schema_doc!(
            "provider_model_display_resolution.json",
            crate::providers::presentation::ProviderModelDisplayResolution
        ),
        schema_doc!(
            "reasoning_effort_row.json",
            crate::providers::presentation::ReasoningEffortRow
        ),
        schema_doc!(
            "reasoning_effort_rows_request.json",
            crate::providers::presentation::ReasoningEffortRowsRequest
        ),
        schema_doc!(
            "reasoning_effort_rows_response.json",
            crate::providers::presentation::ReasoningEffortRowsResponse
        ),
        schema_doc!(
            "gateway_connection_state.json",
            crate::state::client_state::GatewayConnectionState
        ),
        schema_doc!(
            "gateway_endpoint.json",
            crate::gateway::types::GatewayEndpoint
        ),
        schema_doc!(
            "gateway_endpoint_kind.json",
            crate::gateway::types::GatewayEndpointKind
        ),
        schema_doc!(
            "gateway_registry.json",
            crate::gateway::types::GatewayRegistry
        ),
        schema_doc!(
            "gateway_id_pin_validation.json",
            crate::gateway::registry::GatewayIdPinValidation
        ),
        schema_doc!(
            "gateway_session_metadata.json",
            crate::gateway::session_lifecycle::GatewaySessionMetadata
        ),
        schema_doc!(
            "session_terminal_reason.json",
            crate::gateway::session_lifecycle::SessionTerminalReason
        ),
        schema_doc!(
            "gateway_ws_session_identity.json",
            crate::transport::ws::GatewayWsSessionIdentity
        ),
        schema_doc!(
            "remote_gateway_validation.json",
            crate::gateway::setup::RemoteGatewayValidation
        ),
        schema_doc!(
            "activate_gateway_registry_plan.json",
            crate::gateway::setup::ActivateGatewayRegistryPlan
        ),
        schema_doc!(
            "set_gateway_workspace_registry_plan.json",
            crate::gateway::setup::SetGatewayWorkspaceRegistryPlan
        ),
        schema_doc!(
            "update_remote_gateway_registry_plan.json",
            crate::gateway::setup::UpdateRemoteGatewayRegistryPlan
        ),
        schema_doc!(
            "delete_remote_gateway_registry_plan.json",
            crate::gateway::setup::DeleteRemoteGatewayRegistryPlan
        ),
        schema_doc!(
            "gateway_remote_access_status_label.json",
            crate::settings::gateway::GatewayRemoteAccessStatusLabel
        ),
        schema_doc!(
            "gateway_settings_state.json",
            crate::settings::gateway::GatewaySettingsState
        ),
        schema_doc!(
            "gateway_settings_action_scope.json",
            crate::settings::gateway::GatewaySettingsActionScope
        ),
        schema_doc!(
            "gateway_settings_refresh_plan.json",
            crate::settings::gateway::GatewaySettingsRefreshPlan
        ),
        schema_doc!(
            "gateway_settings_refresh_unavailable.json",
            crate::settings::gateway::GatewaySettingsRefreshUnavailable
        ),
        schema_doc!(
            "gateway_settings_update_plan.json",
            crate::settings::gateway::GatewaySettingsUpdatePlan
        ),
        schema_doc!(
            "voice_input_runtime_presentation.json",
            crate::settings::voice::VoiceInputRuntimePresentation
        ),
        schema_doc!(
            "voice_input_settings_action.json",
            crate::settings::voice::VoiceInputSettingsAction
        ),
        schema_doc!(
            "voice_input_settings_plan.json",
            crate::settings::voice::VoiceInputSettingsPlan
        ),
        schema_doc!(
            "voice_input_settings_plan_rejection.json",
            crate::settings::voice::VoiceInputSettingsPlanRejection
        ),
        schema_doc!(
            "voice_input_settings_plan_request.json",
            crate::settings::voice::VoiceInputSettingsPlanRequest
        ),
        schema_doc!(
            "voice_input_status_reduction.json",
            crate::settings::voice::VoiceInputStatusReduction
        ),
        schema_doc!(
            "gateway_status_endpoint.json",
            crate::state::reducers::GatewayStatusEndpoint
        ),
        schema_doc!(
            "gateway_status_level.json",
            crate::state::client_state::GatewayStatusLevel
        ),
        schema_doc!(
            "gateway_status_message.json",
            crate::state::reducers::GatewayStatusMessage
        ),
        schema_doc!(
            "gateway_status_projection.json",
            crate::state::reducers::GatewayStatusProjection
        ),
        schema_doc!(
            "gateway_status_text_update.json",
            crate::state::reducers::GatewayStatusTextUpdate
        ),
        schema_doc!(
            "gateway_ws_event.json",
            crate::transport::ws::GatewayWsEvent
        ),
        schema_doc!(
            "mcp_audit_action.json",
            crate::mcp::presentation::McpAuditAction
        ),
        schema_doc!(
            "mcp_audit_decision.json",
            crate::mcp::presentation::McpAuditDecision
        ),
        schema_doc!(
            "mcp_audit_details_summary.json",
            crate::mcp::presentation::McpAuditDetailsSummary
        ),
        schema_doc!("mcp_audit_row.json", crate::mcp::presentation::McpAuditRow),
        schema_doc!(
            "mcp_capability_count.json",
            crate::mcp::presentation::McpCapabilityCount
        ),
        schema_doc!(
            "mcp_capability_kind.json",
            crate::mcp::presentation::McpCapabilityKind
        ),
        schema_doc!(
            "mcp_capability_selection_toggle.json",
            crate::composer::capabilities::McpCapabilitySelectionToggle
        ),
        schema_doc!(
            "mcp_capability_unavailable_reason.json",
            crate::composer::capabilities::McpCapabilityUnavailableReason
        ),
        schema_doc!(
            "mcp_config_validation_error.json",
            crate::mcp::actions::McpConfigValidationError
        ),
        schema_doc!(
            "mcp_detail_meta_kind.json",
            crate::mcp::presentation::McpDetailMetaKind
        ),
        schema_doc!(
            "mcp_detail_meta_row.json",
            crate::mcp::presentation::McpDetailMetaRow
        ),
        schema_doc!(
            "mcp_detail_value.json",
            crate::mcp::presentation::McpDetailValue
        ),
        schema_doc!(
            "mcp_install_field_error.json",
            crate::mcp::actions::McpInstallFieldError
        ),
        schema_doc!(
            "mcp_install_field_issue.json",
            crate::mcp::actions::McpInstallFieldIssue
        ),
        schema_doc!(
            "mcp_json_value_preview.json",
            crate::mcp::presentation::McpJsonValuePreview
        ),
        schema_doc!("mcp_list_state.json", crate::mcp::list::McpListState),
        schema_doc!(
            "mcp_presentation_tone.json",
            crate::mcp::presentation::McpPresentationTone
        ),
        schema_doc!(
            "mcp_scope_label.json",
            crate::mcp::presentation::McpScopeLabel
        ),
        schema_doc!(
            "mcp_source_label.json",
            crate::mcp::presentation::McpSourceLabel
        ),
        schema_doc!(
            "mcp_status_label.json",
            crate::mcp::presentation::McpStatusLabel
        ),
        schema_doc!(
            "mcp_timeline_metadata.json",
            crate::timeline::labels::McpTimelineMetadata
        ),
        schema_doc!(
            "mcp_transport_presentation.json",
            crate::mcp::presentation::McpTransportPresentation
        ),
        schema_doc!(
            "memory_model_setting.json",
            crate::settings::memory::MemoryModelSetting
        ),
        schema_doc!(
            "memory_setting_toggle.json",
            crate::settings::memory::MemorySettingToggle
        ),
        schema_doc!(
            "self_improvement_model_setting.json",
            crate::settings::self_improvement::SelfImprovementModelSetting
        ),
        schema_doc!(
            "model_provider_selection_update.json",
            crate::composer::model_selection::ModelProviderSelectionUpdate
        ),
        schema_doc!(
            "model_selector_selection.json",
            crate::composer::model_selection::ModelSelectorSelection
        ),
        schema_doc!(
            "parsed_user_attachment.json",
            crate::timeline::labels::ParsedUserAttachment
        ),
        schema_doc!(
            "parsed_user_attachment_kind.json",
            crate::timeline::labels::ParsedUserAttachmentKind
        ),
        schema_doc!(
            "prepared_composer_attachment.json",
            crate::composer::turn_prepare::PreparedComposerAttachment
        ),
        schema_doc!(
            "prepare_composer_turn_request.json",
            crate::composer::turn_prepare::PrepareComposerTurnRequest
        ),
        schema_doc!(
            "prepare_voice_composer_snapshot_request.json",
            crate::composer::turn_prepare::PrepareVoiceComposerSnapshotRequest
        ),
        schema_doc!(
            "prepared_composer_turn.json",
            crate::composer::turn_prepare::PreparedComposerTurn
        ),
        schema_doc!(
            "prepared_voice_composer_snapshot.json",
            crate::composer::turn_prepare::PreparedVoiceComposerSnapshot
        ),
        schema_doc!(
            "voice_composer_snapshot_discard_reduction.json",
            crate::composer::turn_prepare::VoiceComposerSnapshotDiscardReduction
        ),
        schema_doc!(
            "voice_composer_lock_state.json",
            crate::composer::turn_prepare::VoiceComposerLockState
        ),
        schema_doc!(
            "voice_finalize_response_reduction.json",
            crate::voice::VoiceFinalizeResponseReduction
        ),
        schema_doc!(
            "voice_finalize_ui_action.json",
            crate::voice::VoiceFinalizeUiAction
        ),
        schema_doc!(
            "voice_session_result_reduction.json",
            crate::voice::VoiceSessionResultReduction
        ),
        schema_doc!(
            "provider_api_key_action_unavailable.json",
            crate::providers::actions::ProviderApiKeyActionUnavailable
        ),
        schema_doc!(
            "agent_execution_backend.json",
            pioneer_protocol::AgentExecutionBackend
        ),
        schema_doc!(
            "cli_agent_runtime_kind.json",
            pioneer_protocol::CLIAgentRuntimeKind
        ),
        schema_doc!(
            "cli_agent_runtime_sandbox_policy.json",
            pioneer_protocol::CLIAgentRuntimeSandboxPolicy
        ),
        schema_doc!(
            "turn_cli_runtime_options.json",
            pioneer_protocol::TurnCLIRuntimeOptions
        ),
        schema_doc!(
            "turn_reasoning_selection.json",
            pioneer_protocol::TurnReasoningSelection
        ),
        schema_doc!(
            "cli_runtime_get_params.json",
            pioneer_protocol::CLIRuntimeGetParams
        ),
        schema_doc!(
            "cli_runtime_get_response.json",
            pioneer_protocol::CLIRuntimeGetResponse
        ),
        schema_doc!(
            "cli_runtime_list_models_params.json",
            pioneer_protocol::CLIRuntimeListModelsParams
        ),
        schema_doc!(
            "cli_runtime_list_models_response.json",
            pioneer_protocol::CLIRuntimeListModelsResponse
        ),
        schema_doc!(
            "cli_runtime_list_params.json",
            pioneer_protocol::CLIRuntimeListParams
        ),
        schema_doc!(
            "cli_runtime_list_response.json",
            pioneer_protocol::CLIRuntimeListResponse
        ),
        schema_doc!(
            "cli_runtime_thread_binding_get_params.json",
            pioneer_protocol::CLIRuntimeThreadBindingGetParams
        ),
        schema_doc!(
            "cli_runtime_thread_binding_get_response.json",
            pioneer_protocol::CLIRuntimeThreadBindingGetResponse
        ),
        schema_doc!(
            "cli_runtime_thread_binding.json",
            pioneer_protocol::CLIRuntimeThreadBinding
        ),
        schema_doc!(
            "cli_runtime_thread_compact_params.json",
            pioneer_protocol::CLIRuntimeThreadCompactParams
        ),
        schema_doc!(
            "cli_runtime_thread_compact_response.json",
            pioneer_protocol::CLIRuntimeThreadCompactResponse
        ),
        schema_doc!(
            "cli_runtime_thread_fork_params.json",
            pioneer_protocol::CLIRuntimeThreadForkParams
        ),
        schema_doc!(
            "cli_runtime_thread_fork_response.json",
            pioneer_protocol::CLIRuntimeThreadForkResponse
        ),
        schema_doc!(
            "cli_runtime_turn_steer_params.json",
            pioneer_protocol::CLIRuntimeTurnSteerParams
        ),
        schema_doc!(
            "cli_runtime_turn_steer_response.json",
            pioneer_protocol::CLIRuntimeTurnSteerResponse
        ),
        schema_doc!(
            "cli_runtime_review_delivery.json",
            pioneer_protocol::CLIRuntimeReviewDelivery
        ),
        schema_doc!(
            "cli_runtime_review_target.json",
            pioneer_protocol::CLIRuntimeReviewTarget
        ),
        schema_doc!(
            "cli_runtime_review_start_params.json",
            pioneer_protocol::CLIRuntimeReviewStartParams
        ),
        schema_doc!(
            "cli_runtime_review_start_response.json",
            pioneer_protocol::CLIRuntimeReviewStartResponse
        ),
        schema_doc!(
            "cli_runtime_login_start_type.json",
            pioneer_protocol::CLIRuntimeLoginStartType
        ),
        schema_doc!(
            "cli_runtime_login_start_params.json",
            pioneer_protocol::CLIRuntimeLoginStartParams
        ),
        schema_doc!(
            "cli_runtime_login_start_response.json",
            pioneer_protocol::CLIRuntimeLoginStartResponse
        ),
        schema_doc!(
            "cli_runtime_login_cancel_params.json",
            pioneer_protocol::CLIRuntimeLoginCancelParams
        ),
        schema_doc!(
            "cli_runtime_login_cancel_response.json",
            pioneer_protocol::CLIRuntimeLoginCancelResponse
        ),
        schema_doc!(
            "cli_runtime_proxy_set_params.json",
            pioneer_protocol::CLIRuntimeProxySetParams
        ),
        schema_doc!(
            "cli_runtime_proxy_set_response.json",
            pioneer_protocol::CLIRuntimeProxySetResponse
        ),
        schema_doc!(
            "cli_runtime_proxy_delete_params.json",
            pioneer_protocol::CLIRuntimeProxyDeleteParams
        ),
        schema_doc!(
            "cli_runtime_proxy_delete_response.json",
            pioneer_protocol::CLIRuntimeProxyDeleteResponse
        ),
        schema_doc!(
            "cli_runtime_refresh_params.json",
            pioneer_protocol::CLIRuntimeRefreshParams
        ),
        schema_doc!(
            "cli_runtime_refresh_response.json",
            pioneer_protocol::CLIRuntimeRefreshResponse
        ),
        schema_doc!(
            "cli_runtime_status_params.json",
            pioneer_protocol::CLIRuntimeStatusParams
        ),
        schema_doc!(
            "cli_runtime_status_response.json",
            pioneer_protocol::CLIRuntimeStatusResponse
        ),
        schema_doc!(
            "cli_runtime_pending_request.json",
            pioneer_protocol::CLIRuntimePendingRequest
        ),
        schema_doc!(
            "cli_runtime_pending_request_status.json",
            pioneer_protocol::CLIRuntimePendingRequestStatus
        ),
        schema_doc!(
            "cli_runtime_request_kind.json",
            pioneer_protocol::CLIRuntimeRequestKind
        ),
        schema_doc!(
            "cli_runtime_request_resolution.json",
            pioneer_protocol::CLIRuntimeRequestResolution
        ),
        schema_doc!(
            "cli_runtime_status_changed_notification.json",
            pioneer_protocol::CLIRuntimeStatusChangedNotification
        ),
        schema_doc!(
            "cli_runtime_account_updated_notification.json",
            pioneer_protocol::CLIRuntimeAccountUpdatedNotification
        ),
        schema_doc!(
            "cli_runtime_request_opened_notification.json",
            pioneer_protocol::CLIRuntimeRequestOpenedNotification
        ),
        schema_doc!(
            "cli_runtime_request_resolved_notification.json",
            pioneer_protocol::CLIRuntimeRequestResolvedNotification
        ),
        schema_doc!(
            "cli_runtime_request_respond_params.json",
            pioneer_protocol::CLIRuntimeRequestRespondParams
        ),
        schema_doc!(
            "cli_runtime_request_respond_response.json",
            pioneer_protocol::CLIRuntimeRequestRespondResponse
        ),
        schema_doc!(
            "pending_request.json",
            crate::cli_runtime::approvals::PendingRequest
        ),
        schema_doc!(
            "pending_request_action_kind.json",
            crate::cli_runtime::approvals::PendingRequestActionKind
        ),
        schema_doc!(
            "pending_request_available_action.json",
            crate::cli_runtime::approvals::PendingRequestAvailableAction
        ),
        schema_doc!(
            "pending_request_detail_row.json",
            crate::cli_runtime::approvals::PendingRequestDetailRow
        ),
        schema_doc!(
            "pending_request_detail_style.json",
            crate::cli_runtime::approvals::PendingRequestDetailStyle
        ),
        schema_doc!(
            "pending_request_kind.json",
            crate::cli_runtime::approvals::PendingRequestKind
        ),
        schema_doc!(
            "pending_request_origin.json",
            crate::cli_runtime::approvals::PendingRequestOrigin
        ),
        schema_doc!(
            "pending_request_payload.json",
            crate::cli_runtime::approvals::PendingRequestPayload
        ),
        schema_doc!(
            "pending_request_resolution.json",
            crate::cli_runtime::approvals::PendingRequestResolution
        ),
        schema_doc!(
            "pending_request_presentation.json",
            crate::cli_runtime::approvals::PendingRequestPresentation
        ),
        schema_doc!(
            "pending_request_user_input_option.json",
            crate::cli_runtime::approvals::PendingRequestUserInputOption
        ),
        schema_doc!(
            "pending_request_user_input_question.json",
            crate::cli_runtime::approvals::PendingRequestUserInputQuestion
        ),
        schema_doc!(
            "turn_permission_approval_request.json",
            pioneer_protocol::TurnPermissionApprovalRequest
        ),
        schema_doc!(
            "turn_permission_approval_request_detail.json",
            pioneer_protocol::TurnPermissionApprovalRequestDetail
        ),
        schema_doc!(
            "turn_permission_approval_resolution.json",
            pioneer_protocol::TurnPermissionApprovalResolution
        ),
        schema_doc!(
            "turn_permission_request_opened_notification.json",
            pioneer_protocol::TurnPermissionRequestOpenedNotification
        ),
        schema_doc!(
            "turn_permission_request_resolved_notification.json",
            pioneer_protocol::TurnPermissionRequestResolvedNotification
        ),
        schema_doc!(
            "turn_permission_request_respond_params.json",
            pioneer_protocol::TurnPermissionRequestRespondParams
        ),
        schema_doc!(
            "turn_permission_request_respond_response.json",
            pioneer_protocol::TurnPermissionRequestRespondResponse
        ),
        schema_doc!(
            "cli_runtime_apps_changed_notification.json",
            pioneer_protocol::CLIRuntimeAppsChangedNotification
        ),
        schema_doc!(
            "provider_delete_api_key_action_request.json",
            crate::providers::actions::ProviderDeleteApiKeyActionRequest
        ),
        schema_doc!(
            "provider_delete_api_key_plan.json",
            crate::providers::actions::ProviderDeleteApiKeyPlan
        ),
        schema_doc!(
            "provider_filter.json",
            crate::providers::selectors::ProviderFilter
        ),
        schema_doc!(
            "cli_runtime_provider_draft.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraft
        ),
        schema_doc!(
            "cli_runtime_provider_draft_field.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraftField
        ),
        schema_doc!(
            "cli_runtime_provider_draft_mode.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraftMode
        ),
        schema_doc!(
            "cli_runtime_provider_settings_plan.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderSettingsPlan
        ),
        schema_doc!(
            "cli_runtime_provider_settings_rejection.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderSettingsRejection
        ),
        schema_doc!(
            "cli_runtime_provider_diagnostics_bundle.json",
            crate::providers::diagnostics::CLIRuntimeProviderDiagnosticsBundle
        ),
        schema_doc!(
            "provider_configure_params.json",
            pioneer_protocol::ProviderConfigureParams
        ),
        schema_doc!(
            "provider_configure_response.json",
            pioneer_protocol::ProviderConfigureResponse
        ),
        schema_doc!(
            "provider_list_models_params.json",
            pioneer_protocol::ProviderListModelsParams
        ),
        schema_doc!(
            "provider_list_models_response.json",
            pioneer_protocol::ProviderListModelsResponse
        ),
        schema_doc!(
            "provider_list_params.json",
            pioneer_protocol::ProviderListParams
        ),
        schema_doc!(
            "provider_list_refresh_plan.json",
            crate::providers::list::ProviderListRefreshPlan
        ),
        schema_doc!(
            "provider_list_refresh_request.json",
            crate::providers::list::ProviderListRefreshRequest
        ),
        schema_doc!(
            "provider_list_refresh_unavailable.json",
            crate::providers::list::ProviderListRefreshUnavailable
        ),
        schema_doc!(
            "provider_list_response.json",
            pioneer_protocol::ProviderListResponse
        ),
        schema_doc!(
            "provider_model_info.json",
            pioneer_protocol::ProviderModelInfo
        ),
        schema_doc!(
            "provider_model_reasoning_capabilities.json",
            pioneer_protocol::ProviderModelReasoningCapabilities
        ),
        schema_doc!("provider_summary.json", pioneer_protocol::ProviderSummary),
        schema_doc!(
            "reasoning_capability_source.json",
            pioneer_protocol::ReasoningCapabilitySource
        ),
        schema_doc!(
            "runtime_account_snapshot.json",
            pioneer_protocol::RuntimeAccountSnapshot
        ),
        schema_doc!(
            "runtime_capabilities.json",
            pioneer_protocol::RuntimeCapabilities
        ),
        schema_doc!(
            "runtime_diagnostic.json",
            pioneer_protocol::RuntimeDiagnostic
        ),
        schema_doc!(
            "runtime_diagnostic_level.json",
            pioneer_protocol::RuntimeDiagnosticLevel
        ),
        schema_doc!(
            "runtime_model_info.json",
            pioneer_protocol::RuntimeModelInfo
        ),
        schema_doc!("runtime_app_info.json", pioneer_protocol::RuntimeAppInfo),
        schema_doc!("runtime_status.json", pioneer_protocol::RuntimeStatus),
        schema_doc!("runtime_summary.json", pioneer_protocol::RuntimeSummary),
        schema_doc!(
            "provider_set_api_key_action_request.json",
            crate::providers::actions::ProviderSetApiKeyActionRequest
        ),
        schema_doc!(
            "provider_configure_action_request.json",
            crate::providers::actions::ProviderConfigureActionRequest
        ),
        schema_doc!(
            "provider_configure_plan.json",
            crate::providers::actions::ProviderConfigurePlan
        ),
        schema_doc!(
            "cli_runtime_proxy_set_action_request.json",
            crate::providers::actions::CLIRuntimeProxySetActionRequest
        ),
        schema_doc!(
            "cli_runtime_proxy_set_plan.json",
            crate::providers::actions::CLIRuntimeProxySetPlan
        ),
        schema_doc!(
            "cli_runtime_proxy_delete_action_request.json",
            crate::providers::actions::CLIRuntimeProxyDeleteActionRequest
        ),
        schema_doc!(
            "cli_runtime_proxy_delete_plan.json",
            crate::providers::actions::CLIRuntimeProxyDeletePlan
        ),
        schema_doc!(
            "provider_set_api_key_plan.json",
            crate::providers::actions::ProviderSetApiKeyPlan
        ),
        schema_doc!(
            "reconciled_skills_snapshot.json",
            crate::skills::catalog::ReconciledSkillsSnapshot
        ),
        schema_doc!(
            "composer_skill_chip.json",
            crate::composer::skill_selection::ComposerSkillChip
        ),
        schema_doc!(
            "composer_skill_chip_kind.json",
            crate::composer::skill_selection::ComposerSkillChipKind
        ),
        schema_doc!(
            "composer_skill_picker_projection.json",
            crate::composer::skill_selection::ComposerSkillPickerProjection
        ),
        schema_doc!(
            "composer_skill_selection.json",
            crate::composer::skill_selection::ComposerSkillSelection
        ),
        schema_doc!(
            "composer_skill_selection_reduction.json",
            crate::composer::skill_selection::ComposerSkillSelectionReduction
        ),
        schema_doc!(
            "selectable_mcp_capability.json",
            crate::composer::capabilities::SelectableMcpCapability
        ),
        schema_doc!(
            "selectable_packed_skill_capability.json",
            crate::composer::skill_selection::SelectablePackedSkillCapability
        ),
        schema_doc!(
            "selectable_skill_capability.json",
            crate::composer::capabilities::SelectableSkillCapability
        ),
        schema_doc!(
            "selectable_skill_pack_capability.json",
            crate::composer::skill_selection::SelectableSkillPackCapability
        ),
        schema_doc!(
            "skill_audit_action.json",
            crate::skills::presentation::SkillAuditAction
        ),
        schema_doc!(
            "skill_audit_decision.json",
            crate::skills::presentation::SkillAuditDecision
        ),
        schema_doc!(
            "skill_audit_details_summary.json",
            crate::skills::presentation::SkillAuditDetailsSummary
        ),
        schema_doc!(
            "skill_audit_row.json",
            crate::skills::presentation::SkillAuditRow
        ),
        schema_doc!(
            "skill_capability_unavailable_reason.json",
            crate::composer::capabilities::SkillCapabilityUnavailableReason
        ),
        schema_doc!(
            "skill_catalog_state.json",
            crate::skills::catalog::SkillCatalogState
        ),
        schema_doc!(
            "skill_dependency_card.json",
            crate::skills::presentation::SkillDependencyCard
        ),
        schema_doc!(
            "skill_dependency_kind.json",
            crate::skills::presentation::SkillDependencyKind
        ),
        schema_doc!(
            "skill_dependency_status.json",
            crate::skills::presentation::SkillDependencyStatus
        ),
        schema_doc!(
            "skill_detail_diagnostics.json",
            crate::skills::presentation::SkillDetailDiagnostics
        ),
        schema_doc!(
            "skill_diagnostics_table_cell.json",
            crate::skills::presentation::SkillDiagnosticsTableCell
        ),
        schema_doc!(
            "skill_diagnostics_table_row.json",
            crate::skills::presentation::SkillDiagnosticsTableRow
        ),
        schema_doc!(
            "skill_diagnostics_tone.json",
            crate::skills::presentation::SkillDiagnosticsTone
        ),
        schema_doc!(
            "skill_json_value_preview.json",
            crate::skills::presentation::SkillJsonValuePreview
        ),
        schema_doc!(
            "skill_management_projection.json",
            crate::skills::catalog::SkillManagementProjection
        ),
        schema_doc!(
            "skill_pack_management_row.json",
            crate::skills::catalog::SkillPackManagementRow
        ),
        schema_doc!(
            "skill_security_card.json",
            crate::skills::presentation::SkillSecurityCard
        ),
        schema_doc!(
            "skill_security_severity.json",
            crate::skills::presentation::SkillSecuritySeverity
        ),
        schema_doc!(
            "skill_slug_presentation.json",
            crate::skills::presentation::SkillSlugPresentation
        ),
        schema_doc!(
            "skill_source_kind.json",
            crate::skills::presentation::SkillSourceKind
        ),
        schema_doc!(
            "skill_status.json",
            crate::skills::presentation::SkillStatus
        ),
        schema_doc!(
            "skill_summary_presentation.json",
            crate::skills::presentation::SkillSummaryPresentation
        ),
        schema_doc!(
            "skill_trust_gate_card.json",
            crate::skills::presentation::SkillTrustGateCard
        ),
        schema_doc!(
            "skill_trust_gate_decision.json",
            crate::skills::presentation::SkillTrustGateDecision
        ),
        schema_doc!(
            "skill_trust_gate_tool_kind.json",
            crate::skills::presentation::SkillTrustGateToolKind
        ),
        schema_doc!(
            "skill_trust_level.json",
            crate::skills::presentation::SkillTrustLevel
        ),
        schema_doc!(
            "skills_catalog_snapshot.json",
            crate::skills::catalog::SkillsCatalogSnapshot
        ),
        schema_doc!(
            "skills_catalog_split.json",
            crate::skills::catalog::SkillsCatalogSplit
        ),
        schema_doc!(
            "system_event_detail_row.json",
            crate::timeline::labels::SystemEventDetailRow
        ),
        schema_doc!(
            "system_event_presentation.json",
            crate::timeline::labels::SystemEventPresentation
        ),
        schema_doc!(
            "task_review_action.json",
            crate::tasks::review::TaskReviewAction
        ),
        schema_doc!(
            "task_review_action_state.json",
            crate::tasks::review::TaskReviewActionState
        ),
        schema_doc!(
            "task_review_presentation_capabilities.json",
            crate::tasks::review::TaskReviewPresentationCapabilities
        ),
        schema_doc!(
            "task_review_plan_error.json",
            crate::tasks::review::TaskReviewPlanError
        ),
        schema_doc!(
            "task_accept_params.json",
            pioneer_protocol::TaskAcceptParams
        ),
        schema_doc!(
            "task_accept_response.json",
            pioneer_protocol::TaskAcceptResponse
        ),
        schema_doc!(
            "task_revise_params.json",
            pioneer_protocol::TaskReviseParams
        ),
        schema_doc!(
            "task_revise_response.json",
            pioneer_protocol::TaskReviseResponse
        ),
        schema_doc!(
            "task_cancel_params.json",
            pioneer_protocol::TaskCancelParams
        ),
        schema_doc!(
            "task_cancel_response.json",
            pioneer_protocol::TaskCancelResponse
        ),
        schema_doc!(
            "task_user_notification.json",
            pioneer_protocol::TaskUserNotification
        ),
        schema_doc!(
            "task_user_notification_list_params.json",
            pioneer_protocol::TaskUserNotificationListParams
        ),
        schema_doc!(
            "task_user_notification_list_response.json",
            pioneer_protocol::TaskUserNotificationListResponse
        ),
        schema_doc!(
            "task_user_notification_acknowledge_params.json",
            pioneer_protocol::TaskUserNotificationAcknowledgeParams
        ),
        schema_doc!(
            "task_user_notification_acknowledge_response.json",
            pioneer_protocol::TaskUserNotificationAcknowledgeResponse
        ),
        schema_doc!(
            "task_wait_review_display.json",
            crate::timeline::labels::TaskWaitReviewDisplay
        ),
        schema_doc!(
            "task_wait_review_display_item.json",
            crate::timeline::labels::TaskWaitReviewDisplayItem
        ),
        schema_doc!(
            "thread_artifact_cache_entry.json",
            crate::artifacts::state::ThreadArtifactCacheEntry
        ),
        schema_doc!(
            "thread_artifact_filter.json",
            crate::artifacts::state::ThreadArtifactFilter
        ),
        schema_doc!(
            "thread_list_snapshot.json",
            crate::state::snapshot::ThreadListSnapshot
        ),
        schema_doc!(
            "thread_tree_refresh_failure_reduction.json",
            crate::threads::tree::ThreadTreeRefreshFailureReduction
        ),
        schema_doc!(
            "thread_tree_refresh_success_reduction.json",
            crate::threads::tree::ThreadTreeRefreshSuccessReduction
        ),
        schema_doc!(
            "timeline_coalesced_tools_kind.json",
            crate::timeline::rows::TimelineCoalescedToolsKind
        ),
        schema_doc!(
            "timeline_coalesced_tools_row.json",
            crate::timeline::rows::TimelineCoalescedToolsRow
        ),
        schema_doc!(
            "timeline_final_status.json",
            crate::timeline::labels::TimelineFinalStatus
        ),
        schema_doc!(
            "timeline_final_status_kind.json",
            crate::timeline::labels::TimelineFinalStatusKind
        ),
        schema_doc!("timeline_row.json", crate::timeline::rows::TimelineRow),
        schema_doc!(
            "timeline_row_kind.json",
            crate::timeline::rows::TimelineRowKind
        ),
        schema_doc!(
            "turn_work_group_row.json",
            crate::timeline::rows::TurnWorkGroupRow
        ),
        schema_doc!(
            "workspace_snapshot.json",
            crate::state::snapshot::WorkspaceSnapshot
        ),
        schema_doc!(
            "workspace_bootstrap_request.json",
            crate::workspaces::bootstrap::WorkspaceBootstrapRequest
        ),
        schema_doc!(
            "workspace_bootstrap_success_reduction.json",
            crate::workspaces::actions::WorkspaceBootstrapSuccessReduction
        ),
        schema_doc!(
            "workspace_selection_reduction.json",
            crate::workspaces::actions::WorkspaceSelectionReduction
        ),
        schema_doc!("invitation_status.json", pioneer_protocol::InvitationStatus),
        schema_doc!(
            "invitation_revoke_reason.json",
            pioneer_protocol::InvitationRevokeReason
        ),
        schema_doc!(
            "invitation_transport_security.json",
            pioneer_protocol::InvitationTransportSecurity
        ),
        schema_doc!(
            "invitation_create_params.json",
            pioneer_protocol::InvitationCreateParams
        ),
        schema_doc!(
            "invitation_create_response.json",
            pioneer_protocol::InvitationCreateResponse
        ),
        schema_doc!(
            "invitation_list_params.json",
            pioneer_protocol::InvitationListParams
        ),
        schema_doc!(
            "invitation_list_response.json",
            pioneer_protocol::InvitationListResponse
        ),
        schema_doc!(
            "invitation_revoke_params.json",
            pioneer_protocol::InvitationRevokeParams
        ),
        schema_doc!(
            "invitation_revoke_response.json",
            pioneer_protocol::InvitationRevokeResponse
        ),
        schema_doc!(
            "invitation_preview_response.json",
            pioneer_protocol::InvitationPreviewResponse
        ),
        schema_doc!(
            "invitation_accept_params.json",
            pioneer_protocol::InvitationAcceptParams
        ),
        schema_doc!(
            "invitation_accept_response.json",
            pioneer_protocol::InvitationAcceptResponse
        ),
        schema_doc!(
            "invitation_changed_notification.json",
            pioneer_protocol::InvitationChangedNotification
        ),
        schema_doc!(
            "profile_avatar_media_type.json",
            pioneer_protocol::ProfileAvatarMediaType
        ),
        schema_doc!(
            "profile_avatar_input.json",
            pioneer_protocol::ProfileAvatarInput
        ),
        schema_doc!(
            "new_member_profile.json",
            pioneer_protocol::NewMemberProfile
        ),
        schema_doc!("member_summary.json", pioneer_protocol::MemberSummary),
        schema_doc!(
            "member_list_params.json",
            pioneer_protocol::MemberListParams
        ),
        schema_doc!(
            "member_list_response.json",
            pioneer_protocol::MemberListResponse
        ),
        schema_doc!(
            "member_suspend_params.json",
            pioneer_protocol::MemberSuspendParams
        ),
        schema_doc!(
            "member_restore_params.json",
            pioneer_protocol::MemberRestoreParams
        ),
        schema_doc!(
            "member_remove_params.json",
            pioneer_protocol::MemberRemoveParams
        ),
        schema_doc!(
            "member_mutation_response.json",
            pioneer_protocol::MemberMutationResponse
        ),
        schema_doc!(
            "member_device_create_params.json",
            pioneer_protocol::MemberDeviceCreateParams
        ),
        schema_doc!(
            "member_device_create_response.json",
            pioneer_protocol::MemberDeviceCreateResponse
        ),
        schema_doc!(
            "workspace_member_list_params.json",
            pioneer_protocol::WorkspaceMemberListParams
        ),
        schema_doc!(
            "workspace_member_list_response.json",
            pioneer_protocol::WorkspaceMemberListResponse
        ),
        schema_doc!(
            "workspace_member_add_params.json",
            pioneer_protocol::WorkspaceMemberAddParams
        ),
        schema_doc!(
            "workspace_member_remove_params.json",
            pioneer_protocol::WorkspaceMemberRemoveParams
        ),
        schema_doc!(
            "workspace_member_mutation_response.json",
            pioneer_protocol::WorkspaceMemberMutationResponse
        ),
        schema_doc!(
            "thread_participants_list_params.json",
            pioneer_protocol::ThreadParticipantsListParams
        ),
        schema_doc!(
            "thread_participant_mutation_params.json",
            pioneer_protocol::ThreadParticipantMutationParams
        ),
        schema_doc!(
            "thread_participants_response.json",
            pioneer_protocol::ThreadParticipantsResponse
        ),
        schema_doc!(
            "authorization_capabilities_params.json",
            pioneer_protocol::AuthorizationCapabilitiesParams
        ),
        schema_doc!(
            "authorization_capability_snapshot.json",
            pioneer_protocol::AuthorizationCapabilitySnapshot
        ),
        schema_doc!(
            "thread_update_params.json",
            pioneer_protocol::ThreadUpdateParams
        ),
        schema_doc!(
            "thread_update_response.json",
            pioneer_protocol::ThreadUpdateResponse
        ),
        schema_doc!(
            "principal_presentation_capabilities.json",
            crate::authorization::PrincipalPresentationCapabilities
        ),
        schema_doc!(
            "current_principal_presentation.json",
            crate::authorization::CurrentPrincipalPresentation
        ),
        schema_doc!(
            "session_list_row_presentation.json",
            crate::authorization::SessionListRowPresentation
        ),
        schema_doc!(
            "thread_create_visibility_plan.json",
            crate::threads::scope::ThreadCreateVisibilityPlan
        ),
        schema_doc!(
            "thread_scope_presentation.json",
            crate::threads::scope::ThreadScopePresentation
        ),
        schema_doc!(
            "thread_scope_mutation_plan.json",
            crate::threads::scope::ThreadScopeMutationPlan
        ),
        schema_doc!(
            "administration_refetch.json",
            crate::administration::AdministrationRefetch
        ),
        schema_doc!(
            "administration_action.json",
            crate::administration::AdministrationAction
        ),
        schema_doc!(
            "invitation_list_row.json",
            crate::administration::InvitationListRow
        ),
        schema_doc!("member_list_row.json", crate::administration::MemberListRow),
        schema_doc!(
            "message_revision_presentation.json",
            crate::timeline::rows::MessageRevisionPresentation
        ),
        schema_doc!(
            "message_revision_page_presentation.json",
            crate::timeline::rows::MessageRevisionPagePresentation
        ),
        schema_doc!(
            "member_changed_notification.json",
            pioneer_protocol::MemberChangedNotification
        ),
        schema_doc!(
            "workspace_members_changed_notification.json",
            pioneer_protocol::WorkspaceMembersChangedNotification
        ),
    ];

    documents.sort_by(|left, right| left.file_name.cmp(right.file_name));
    documents
}

#[cfg(any(feature = "schema", test))]
pub fn write_client_schemas(
    output_directory: impl AsRef<Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    let output_directory = output_directory.as_ref();
    fs::create_dir_all(output_directory)?;

    for document in client_schema_documents() {
        let schema_json = serde_json::to_string_pretty(&document.schema)?;
        let path = output_directory.join(document.file_name);
        fs::write(path, schema_json)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value as JsonValue;
    use std::fs;

    #[test]
    fn schema_documents_match_public_contract_boundary() {
        let contract_files = client_contract_types()
            .into_iter()
            .map(|contract| contract.file_name)
            .collect::<Vec<_>>();
        let schema_files = client_schema_documents()
            .into_iter()
            .map(|document| document.file_name)
            .collect::<Vec<_>>();

        assert_eq!(schema_files, contract_files);
    }

    #[test]
    fn schema_documents_are_sorted_unique_and_serializable() {
        let documents = client_schema_documents();
        let file_names = documents
            .iter()
            .map(|document| document.file_name)
            .collect::<Vec<_>>();
        let mut sorted = file_names.clone();
        sorted.sort_unstable();
        sorted.dedup();

        assert_eq!(file_names, sorted);

        for document in documents {
            let schema_json =
                serde_json::to_string_pretty(&document.schema).expect("schema serializes");
            let schema_value: JsonValue =
                serde_json::from_str(&schema_json).expect("schema JSON parses");

            assert!(
                schema_value.is_object(),
                "{} should serialize to a JSON object",
                document.file_name
            );
        }
    }

    #[test]
    fn native_storage_effect_schemas_export_typed_completions() {
        for document in client_schema_documents().into_iter().filter(|document| {
            matches!(
                document.file_name,
                "client_effect_plan.json" | "client_effect_completion.json"
            )
        }) {
            let json = serde_json::to_string_pretty(&document.schema).unwrap();
            assert!(json.contains("GatewaySession") || json.contains("gateway_session"));
            if std::env::var_os("PIONEER_PRINT_PUBLICATION_SCHEMAS").is_some() {
                println!("SCHEMA_BEGIN:{}\n{json}\nSCHEMA_END", document.file_name);
            }
        }
    }

    #[test]
    fn gateway_settings_store_schema_exports_scoped_state() {
        let schema = schema_for!(crate::gateway::settings_store::GatewaySettingsStore);
        let json = serde_json::to_string_pretty(&schema).unwrap();
        assert!(json.contains("loading"));
        assert!(json.contains("saving"));
        if std::env::var_os("PIONEER_PRINT_SETTINGS_SCHEMA").is_some() {
            println!("SETTINGS_SCHEMA_BEGIN\n{json}\nSETTINGS_SCHEMA_END");
        }
    }

    #[test]
    fn identity_authorization_publication_schema_contains_no_credentials() {
        let schema =
            schema_for!(crate::gateway::identity_authorization::IdentityAuthorizationPublication);
        let json = serde_json::to_string_pretty(&schema).unwrap();
        for forbidden in ["refresh_token", "access_token", "credential"] {
            assert!(!json.contains(&format!("\"{forbidden}\"")));
        }
        if std::env::var_os("PIONEER_PRINT_IDENTITY_SCHEMA").is_some() {
            println!("IDENTITY_SCHEMA_BEGIN\n{json}\nIDENTITY_SCHEMA_END");
        }
    }

    #[test]
    fn gateway_session_publication_schema_contains_no_credentials() {
        let schema = schema_for!(crate::gateway::session_controller::GatewaySessionPublication);
        let json = serde_json::to_string_pretty(&schema).unwrap();
        for forbidden in ["refresh_token", "access_token", "credential"] {
            assert!(!json.contains(&format!("\"{forbidden}\"")));
        }
        if std::env::var_os("PIONEER_PRINT_SESSION_SCHEMA").is_some() {
            println!("SESSION_SCHEMA_BEGIN\n{json}\nSESSION_SCHEMA_END");
        }
    }

    #[test]
    fn schema_export_is_reproducible_across_directories() {
        let left = tempfile::tempdir().expect("left schema tempdir");
        let right = tempfile::tempdir().expect("right schema tempdir");

        write_client_schemas(left.path()).expect("left schema export");
        write_client_schemas(right.path()).expect("right schema export");

        let file_names = client_schema_documents()
            .into_iter()
            .map(|document| document.file_name)
            .collect::<Vec<_>>();

        for file_name in file_names {
            let left_bytes = fs::read(left.path().join(file_name)).expect("left schema file");
            let right_bytes = fs::read(right.path().join(file_name)).expect("right schema file");

            assert_eq!(
                left_bytes, right_bytes,
                "{file_name} changed between exports"
            );
        }
    }

    #[test]
    fn skill_pack_composer_contracts_are_registered() {
        let file_names = client_schema_documents()
            .into_iter()
            .map(|document| document.file_name)
            .collect::<Vec<_>>();

        for expected in [
            "composer_skill_chip.json",
            "composer_skill_picker_projection.json",
            "composer_skill_selection.json",
            "composer_skill_selection_reduction.json",
            "selectable_packed_skill_capability.json",
            "selectable_skill_pack_capability.json",
            "skill_management_projection.json",
            "skill_pack_management_row.json",
        ] {
            assert!(
                file_names.contains(&expected),
                "missing skill pack contract {expected}"
            );
        }
    }

    #[test]
    fn auth_session_metadata_contracts_are_registered_and_events_are_secret_free() {
        let documents = client_schema_documents();
        let file_names = documents
            .iter()
            .map(|document| document.file_name)
            .collect::<Vec<_>>();

        for expected in [
            "gateway_id_pin_validation.json",
            "gateway_session_metadata.json",
            "session_terminal_reason.json",
            "gateway_ws_session_identity.json",
        ] {
            assert!(
                file_names.contains(&expected),
                "missing auth contract {expected}"
            );
        }

        for (file_name, contract_name) in [
            ("gateway_ws_event.json", "GatewayWsEvent"),
            ("client_snapshot.json", "ClientSnapshot"),
        ] {
            let document = documents
                .iter()
                .find(|document| document.file_name == file_name)
                .unwrap_or_else(|| panic!("missing {contract_name} schema"));
            let schema = serde_json::to_string(&document.schema).expect("schema serializes");
            for forbidden in ["access_token", "refresh_token", "activation_code"] {
                assert!(
                    !schema.contains(forbidden),
                    "{contract_name} exposes secret field `{forbidden}`"
                );
            }
        }
    }
}
