//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_work_branch_schedule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub root_execution_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub branch_key: String,
    pub last_scheduled_at: Option<DateTimeWithTimeZone>,
    pub last_scheduled_sequence: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "root_execution_id",
        to = "root_execution_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_work_resource_scope: HasOne<super::agent_work_resource_scope::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
