//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_memory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_agent_memory_active_key")]
    pub scope_kind: String,
    #[sea_orm(column_type = "Text")]
    pub scope_key: String,
    #[sea_orm(unique_key = "uidx_agent_memory_active_key")]
    pub scope_key_hash: String,
    pub workspace_id: Option<String>,
    #[sea_orm(unique_key = "uidx_agent_memory_active_key")]
    pub namespace: String,
    pub category: String,
    pub key: Option<String>,
    #[sea_orm(unique_key = "uidx_agent_memory_active_key")]
    pub active_key: Option<String>,
    pub status: String,
    pub sensitivity: String,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    #[sea_orm(column_type = "Double")]
    pub importance: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_preview: Option<String>,
    pub capsule_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub capsule_ref: Option<String>,
    pub frame_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub frame_uri: Option<String>,
    pub frame_version: i64,
    pub source_kind: String,
    pub source_context_kind: Option<String>,
    pub source_thread_id: Option<String>,
    pub source_turn_id: Option<String>,
    pub source_item_id: Option<String>,
    pub created_by_kind: Option<String>,
    pub created_by_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_accessed_at: Option<DateTimeWithTimeZone>,
    pub access_count: i64,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub superseded_by: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub deleted_by_kind: Option<String>,
    pub deleted_by_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub delete_reason: Option<String>,
    pub policy_version: Option<String>,
    pub repair_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
