//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_action_receipt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub action_id: String,
    pub actor_kind: String,
    pub actor_id: Option<String>,
    pub decision: String,
    pub policy_fingerprint: String,
    pub execution_grant_fingerprint: Option<String>,
    pub execution_grant_policy_generation: Option<i64>,
    pub source_scope_id: Option<String>,
    pub destination_scope_id: Option<String>,
    pub action_kind: Option<String>,
    pub authorized_resource_action: Option<String>,
    pub subject_role_key: Option<String>,
    pub execution_generation: Option<i64>,
    pub source_policy_generation: Option<i64>,
    pub destination_policy_generation: Option<i64>,
    pub route_generation: Option<i64>,
    pub disclosure_class: Option<String>,
    pub decision_fingerprint: Option<String>,
    pub committed_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub route_receipt_json: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "action_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_action: HasOne<super::agent_action::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
