//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_delegation_route")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub source_execution_id: String,
    pub destination_thread_id: String,
    pub destination_agent_identity_id: Option<String>,
    pub home_capsule_id: Option<String>,
    pub route_kind: String,
    pub grant_fingerprint: String,
    pub source_capsule_id: Option<String>,
    pub destination_capsule_id: Option<String>,
    pub source_workspace_id: Option<String>,
    pub destination_workspace_id: Option<String>,
    pub source_gateway_id: Option<String>,
    pub destination_gateway_id: Option<String>,
    pub source_identity_id: Option<String>,
    pub destination_profile_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub allowed_actions_json: String,
    #[sea_orm(column_type = "Text")]
    pub disclosure_json: String,
    pub route_generation: i64,
    pub source_policy_generation: i64,
    pub destination_policy_generation: i64,
    pub hop_count: i64,
    pub max_hops: i64,
    pub return_route_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub authority_actor_json: Option<String>,
    pub authority_fingerprint: Option<String>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub agent_delegation_route_events: HasMany<super::agent_delegation_route_event::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
