//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_memory_quarantine")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub memory_id: String,
    pub workspace_id: Option<String>,
    pub reason_code: String,
    pub actor_kind: String,
    pub actor_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub resolved_reason_code: Option<String>,
    pub resolved_actor_kind: Option<String>,
    pub resolved_actor_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub details_json: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
