//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_identity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_identity_workspace_source")]
    pub workspace_id: String,
    #[sea_orm(unique_key = "uq_agent_identity_workspace_source")]
    pub source_kind: String,
    #[sea_orm(unique_key = "uq_agent_identity_workspace_source")]
    pub source_id: String,
    pub source_revision: i64,
    pub source_fingerprint: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub retired_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub agent_executions: HasMany<super::agent_execution::Entity>,
    #[sea_orm(has_many)]
    pub agent_execution_grants: HasMany<super::agent_execution_grant::Entity>,
    #[sea_orm(has_many)]
    pub agent_presentation_snapshots: HasMany<super::agent_presentation_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspace: HasOne<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
