//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_turn_response_execution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub turn_id: String,
    pub execution_id: String,
    pub presentation_snapshot_id: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
    #[sea_orm(
        belongs_to,
        from = "presentation_snapshot_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_presentation_snapshot: HasOne<super::agent_presentation_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
