//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_memory_quality_decision")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub item_id: Option<String>,
    pub task_id: Option<String>,
    pub memory_id: Option<String>,
    pub candidate_id: Option<String>,
    pub canonical_key: Option<String>,
    pub action: String,
    pub target_ownership: String,
    pub source_context_kind: String,
    pub fact_class: String,
    pub lifetime_class: String,
    pub ownership_class: String,
    pub evidence_class: String,
    pub relation: String,
    #[sea_orm(column_type = "Text")]
    pub reason_codes_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_snapshot_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
