//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_action_timeline_target")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_key: String,
    #[sea_orm(unique)]
    pub action_id: String,
    pub turn_id: String,
    #[sea_orm(unique)]
    pub turn_item_id: Option<String>,
    pub target_kind: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "action_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_action: HasOne<super::agent_action::Entity>,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub turn: HasOne<super::turn::Entity>,
    #[sea_orm(
        belongs_to,
        from = "turn_item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub turn_item: HasOne<super::turn_item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
