//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_presentation_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_presentation_snapshot_source")]
    pub agent_identity_id: String,
    #[sea_orm(unique_key = "uq_agent_presentation_snapshot_source")]
    pub source_revision: i64,
    #[sea_orm(unique_key = "uq_agent_presentation_snapshot_source")]
    pub source_fingerprint: String,
    pub display_name: String,
    pub nickname: String,
    pub avatar_revision: Option<String>,
    pub role_label: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub agent_executions: HasMany<super::agent_execution::Entity>,
    #[sea_orm(
        belongs_to,
        from = "agent_identity_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_identity: HasOne<super::agent_identity::Entity>,
    #[sea_orm(has_many)]
    pub agent_turn_response_executions: HasMany<super::agent_turn_response_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
