//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_memory_identity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub scope_kind: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub scope_key_hash: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub namespace: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub canonical_key: String,
    #[sea_orm(column_type = "Text", unique)]
    pub memory_id: String,
    #[sea_orm(
        belongs_to,
        from = "memory_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_memory: HasOne<super::agent_memory::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
