//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_execution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub agent_identity_id: String,
    pub identity_source_revision: i64,
    pub identity_source_fingerprint: String,
    pub parent_execution_id: Option<String>,
    pub parent_task_id: Option<String>,
    pub parent_thread_id: Option<String>,
    pub home_root_thread_id: String,
    pub work_graph_root_execution_id: String,
    #[sea_orm(column_type = "Text")]
    pub requested_identity_selection_json: String,
    #[sea_orm(column_type = "Text")]
    pub requested_profile_selection_json: String,
    pub resolved_profile_id: Option<String>,
    pub resolved_profile_fingerprint: Option<String>,
    pub presentation_snapshot_id: Option<String>,
    pub authorization_context_fingerprint: String,
    pub execution_generation: i64,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub agent_actions: HasMany<super::agent_action::Entity>,
    #[sea_orm(has_many)]
    pub agent_action_outboxes: HasMany<super::agent_action_outbox::Entity>,
    #[sea_orm(has_many)]
    pub agent_delegation_routes: HasMany<super::agent_delegation_route::Entity>,
    #[sea_orm(has_many)]
    pub agent_execution_grants: HasMany<super::agent_execution_grant::Entity>,
    #[sea_orm(has_many)]
    pub agent_execution_resource_states: HasMany<super::agent_execution_resource_state::Entity>,
    #[sea_orm(
        belongs_to,
        from = "agent_identity_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_identity: HasOne<super::agent_identity::Entity>,
    #[sea_orm(
        belongs_to,
        from = "presentation_snapshot_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_presentation_snapshot: HasOne<super::agent_presentation_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub agent_turn_response_executions: HasMany<super::agent_turn_response_execution::Entity>,
    #[sea_orm(has_one)]
    pub agent_work_resource_scope: HasOne<super::agent_work_resource_scope::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspace: HasOne<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
