//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_delegation_route_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_route_event_generation")]
    pub route_id: String,
    pub event_kind: String,
    #[sea_orm(unique_key = "uq_agent_route_event_generation")]
    pub route_generation: i64,
    #[sea_orm(column_type = "Text")]
    pub authority_actor_json: String,
    pub authority_fingerprint: String,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "route_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_delegation_route: HasOne<super::agent_delegation_route::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
