//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_execution_resource_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_resource_state_attempt")]
    pub execution_id: String,
    #[sea_orm(unique_key = "uq_agent_resource_state_attempt")]
    pub attempt_generation: i64,
    pub progress_sequence: i64,
    #[sea_orm(column_type = "Text")]
    pub progress_frontier_json: String,
    pub last_progress_at: Option<DateTimeWithTimeZone>,
    pub last_heartbeat_at: Option<DateTimeWithTimeZone>,
    pub idle_deadline: Option<DateTimeWithTimeZone>,
    pub hard_deadline: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub local_usage_json: String,
    pub permit_id: Option<String>,
    pub branch_key: String,
    pub fair_order: i64,
    pub status: String,
    pub fencing_generation: i64,
    pub fenced_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
