//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_domain_commit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub mutation_kind: String,
    #[sea_orm(unique_key = "uq_agent_domain_commit_execution_idempotency")]
    pub idempotency_key: String,
    pub request_fingerprint: String,
    #[sea_orm(unique_key = "uq_agent_domain_commit_execution_idempotency")]
    pub execution_id: String,
    pub actor_identity_id: String,
    #[sea_orm(unique)]
    pub receipt_id: String,
    #[sea_orm(unique)]
    pub outbox_id: String,
    pub status: String,
    pub committed_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
