//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_memory_capsule")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_agent_memory_capsule_scope_slot")]
    pub scope_kind: String,
    #[sea_orm(column_type = "Text")]
    pub scope_key: String,
    #[sea_orm(unique_key = "uidx_agent_memory_capsule_scope_slot")]
    pub scope_key_hash: String,
    #[sea_orm(unique_key = "uidx_agent_memory_capsule_scope_slot")]
    pub scope_slot: String,
    #[sea_orm(column_type = "Text", unique)]
    pub capsule_ref: String,
    #[sea_orm(column_type = "Text")]
    pub storage_uri: String,
    pub backend: String,
    pub format: String,
    pub encrypted: bool,
    pub status: String,
    pub repair_status: String,
    pub content_hash: Option<String>,
    pub active_record_count: i64,
    pub last_compacted_at: Option<DateTimeWithTimeZone>,
    pub last_reindexed_at: Option<DateTimeWithTimeZone>,
    pub last_verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
