//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_execution_grant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub execution_id: String,
    pub parent_execution_id: Option<String>,
    pub child_identity_id: String,
    pub grant_fingerprint: String,
    #[sea_orm(column_type = "Text")]
    pub grant_json: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
    #[sea_orm(
        belongs_to,
        from = "child_identity_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub agent_identity: HasOne<super::agent_identity::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
