//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_running_permit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_running_permit_attempt")]
    pub root_execution_id: String,
    #[sea_orm(unique_key = "uq_agent_running_permit_attempt")]
    pub execution_id: String,
    #[sea_orm(unique_key = "uq_agent_running_permit_attempt")]
    pub attempt_generation: i64,
    pub lease_generation: i64,
    pub status: String,
    pub acquired_at: DateTimeWithTimeZone,
    pub released_at: Option<DateTimeWithTimeZone>,
    pub fenced_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        relation_enum = "AgentExecution2",
        from = "execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution_2: HasOne<super::agent_execution::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "AgentExecution1",
        from = "root_execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution_1: HasOne<super::agent_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
