//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_work_resource_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub root_execution_id: String,
    pub scope_generation: i64,
    pub max_concurrency: i64,
    pub max_queue_depth: i64,
    pub max_depth: i64,
    pub max_fan_out: i64,
    pub max_total_nodes: i64,
    #[sea_orm(column_type = "Text")]
    pub aggregate_usage_json: String,
    pub queue_generation: i64,
    pub last_scheduled_sequence: i64,
    pub last_scheduled_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "root_execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
    #[sea_orm(has_many)]
    pub agent_work_branch_schedules: HasMany<super::agent_work_branch_schedule::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
