//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_action")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_agent_action_idempotency")]
    pub execution_id: String,
    pub action_kind: String,
    #[sea_orm(unique_key = "uq_agent_action_idempotency")]
    pub idempotency_key: String,
    pub request_fingerprint: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub committed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_json: Option<String>,
    #[sea_orm(has_one)]
    pub agent_action_outbox: HasOne<super::agent_action_outbox::Entity>,
    #[sea_orm(has_one)]
    pub agent_action_receipt: HasOne<super::agent_action_receipt::Entity>,
    #[sea_orm(has_one)]
    pub agent_action_timeline_target: HasOne<super::agent_action_timeline_target::Entity>,
    #[sea_orm(
        belongs_to,
        from = "execution_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_execution: HasOne<super::agent_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
