//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_blob")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_artifact_blob_workspace_sha_size_backend")]
    pub workspace_id: String,
    #[sea_orm(unique_key = "uidx_artifact_blob_workspace_sha_size_backend")]
    pub sha256: String,
    #[sea_orm(unique_key = "uidx_artifact_blob_workspace_sha_size_backend")]
    pub size_bytes: i64,
    pub mime_type: Option<String>,
    #[sea_orm(unique_key = "uidx_artifact_blob_workspace_sha_size_backend")]
    pub storage_backend: String,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub encryption_key_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub last_verified_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
}

impl ActiveModelBehavior for ActiveModel {}
