//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_upload_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub message_id: Option<String>,
    pub display_name: String,
    pub expected_size_bytes: Option<i64>,
    pub expected_sha256: Option<String>,
    pub mime_type: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub temp_storage_key: String,
    pub received_bytes: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
}

impl ActiveModelBehavior for ActiveModel {}
