//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "artifact_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub artifact_id: String,
    pub artifact_version_id: Option<String>,
    pub workspace_id: String,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub message_id: Option<String>,
    pub turn_item_id: Option<String>,
    pub tool_call_id: Option<String>,
    pub task_id: Option<String>,
    pub task_run_id: Option<String>,
    pub binding_kind: String,
    pub direction: String,
    pub item_index: Option<i64>,
    pub role: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
}

impl ActiveModelBehavior for ActiveModel {}
