//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "attachment_upload_registry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub registry_key: String,
    pub provider: String,
    pub model_family: String,
    pub transport_kind: String,
    pub sha256: String,
    #[sea_orm(column_type = "Text")]
    pub provider_file_id: String,
    pub uploaded_at_unix_ms: i64,
    pub ttl_secs: i64,
    pub expires_at_unix_ms: i64,
    pub mime_type: String,
    pub size_bytes: i64,
    pub file_name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
