//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub gateway_id: String,
    pub actor_principal_id: Option<String>,
    pub actor_session_id: Option<String>,
    pub action: String,
    pub domain: String,
    pub target_kind: String,
    pub target_id: String,
    pub workspace_id: Option<String>,
    pub metadata_version: i64,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "actor_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub auth_session: HasOne<super::auth_session::Entity>,
    #[sea_orm(
        belongs_to,
        from = "gateway_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_identity: HasOne<super::gateway_identity::Entity>,
    #[sea_orm(
        belongs_to,
        from = "actor_principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal: HasOne<super::gateway_principal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
