//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_refresh_credential")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub session_id: String,
    #[sea_orm(unique)]
    pub token_family_id: String,
    pub generation: i64,
    #[sea_orm(column_type = "Binary(1)", unique)]
    pub token_hash: Vec<u8>,
    pub issued_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub auth_session: HasOne<super::auth_session::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
