//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "idx_auth_session_pending_activation_locator_hash")]
    pub gateway_id: String,
    #[sea_orm(unique_key = "idx_auth_session_pending_local")]
    pub principal_id: String,
    #[sea_orm(unique)]
    pub device_id: String,
    #[sea_orm(unique)]
    pub token_family_id: String,
    #[sea_orm(unique)]
    pub created_by_session_id: Option<String>,
    #[sea_orm(column_type = "Binary(1)")]
    pub activation_token_hash: Vec<u8>,
    #[sea_orm(
        column_type = "Binary(1)",
        unique_key = "idx_auth_session_pending_activation_locator_hash"
    )]
    pub activation_locator_hash: Vec<u8>,
    pub activation_failed_attempts: i64,
    pub activation_expires_at: DateTimeWithTimeZone,
    pub activated_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub refresh_generation: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub last_refreshed_at: Option<DateTimeWithTimeZone>,
    pub refresh_expires_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub revoke_reason: Option<String>,
    #[sea_orm(has_one)]
    pub auth_refresh_credential: HasOne<super::auth_refresh_credential::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "created_by_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub auth_session: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "device_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub device: HasOne<super::device::Entity>,
    #[sea_orm(
        belongs_to,
        from = "gateway_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_identity: HasOne<super::gateway_identity::Entity>,
    #[sea_orm(
        belongs_to,
        from = "principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal: HasOne<super::gateway_principal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
