//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "authorization_policy_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub singleton_id: i64,
    pub generation: i64,
    pub code_policy_fingerprint: String,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
