//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_refresh_credential")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub session_id: String,
    pub token_family_id: String,
    #[sea_orm(unique_key = "idx_auth_refresh_generation")]
    pub generation: i64,
    #[sea_orm(column_type = "Binary(1)", unique)]
    pub token_hash: Vec<u8>,
    pub status: String,
    pub issued_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    pub replaced_by_id: Option<String>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "replaced_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub auth_refresh_credential: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub auth_session: HasOne<super::auth_session::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
