//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cli_runtime_native_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub runtime_id: String,
    pub runtime_kind: String,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_thread_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_turn_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub native_method: String,
    #[sea_orm(column_type = "Text")]
    pub payload_redacted_json: String,
    pub sequence: i64,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
