//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cli_runtime_pending_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub request_id: String,
    pub runtime_id: String,
    pub runtime_kind: String,
    pub workspace_id: String,
    pub thread_id: String,
    pub turn_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_thread_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_turn_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_item_id: Option<String>,
    pub request_kind: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub initiating_principal_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub initiating_session_id: Option<String>,
    pub initiating_session_generation: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_context_fingerprint: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
