//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_task_output")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub task_run_turn_id: String,
    #[sea_orm(column_type = "Text")]
    pub task_id: String,
    #[sea_orm(column_type = "Text")]
    pub run_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub source_thread: String,
    #[sea_orm(column_type = "Text")]
    pub source_turn: String,
    #[sea_orm(column_type = "Text")]
    pub manifest_id: String,
    #[sea_orm(has_many)]
    pub compaction_delivery_outputs: HasMany<super::compaction_delivery_output::Entity>,
    #[sea_orm(
        belongs_to,
        from = "manifest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub compaction_frozen_history: HasOne<super::compaction_frozen_history::Entity>,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task_run: HasOne<super::task_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "task_run_turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task_run_turn: HasOne<super::task_run_turn::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_thread",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub thread: HasOne<super::thread::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_turn",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub turn: HasOne<super::turn::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspace: HasOne<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
