//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_frozen_import")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub manifest_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ordinal: i64,
    pub message_ordinal: i64,
    #[sea_orm(column_type = "Text")]
    pub source_scope: String,
    #[sea_orm(column_type = "Text")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub source_version: String,
    #[sea_orm(column_type = "Text")]
    pub source_thread: String,
    #[sea_orm(column_type = "Text")]
    pub proof_json: String,
    pub bytes: i64,
    #[sea_orm(
        belongs_to,
        from = "manifest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_frozen_history: HasOne<super::compaction_frozen_history::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
