//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_frozen_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub owner_thread: String,
    #[sea_orm(column_type = "Text")]
    pub identity_sha256: String,
    pub message_count: i64,
    pub next_ordinal: i64,
    pub import_count: i64,
    #[sea_orm(column_type = "Text")]
    pub imports_sha256: String,
    pub next_import: i64,
    pub ready: i64,
    #[sea_orm(has_many)]
    pub compaction_frozen_imports: HasMany<super::compaction_frozen_import::Entity>,
    #[sea_orm(has_many)]
    pub compaction_frozen_messages: HasMany<super::compaction_frozen_message::Entity>,
    #[sea_orm(has_many)]
    pub compaction_operation_projections: HasMany<super::compaction_operation_projection::Entity>,
    #[sea_orm(has_many)]
    pub compaction_task_outputs: HasMany<super::compaction_task_output::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_thread",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub thread: HasOne<super::thread::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspace: HasOne<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
