//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_delivery_output")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub delivery_id: String,
    #[sea_orm(column_type = "Text")]
    pub candidate_id: String,
    #[sea_orm(column_type = "Text")]
    pub task_run_turn_id: String,
    #[sea_orm(
        belongs_to,
        from = "task_run_turn_id",
        to = "task_run_turn_id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_task_output: HasOne<super::compaction_task_output::Entity>,
    #[sea_orm(
        belongs_to,
        from = "delivery_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task_delivery: HasOne<super::task_delivery::Entity>,
    #[sea_orm(
        belongs_to,
        from = "candidate_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task_result_candidate: HasOne<super::task_result_candidate::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
