//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_frozen_layout")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub manifest_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub kind: i64,
    pub active: i64,
    pub pending: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub candidate: Option<String>,
    pub compared: i64,
    pub copy_to: Option<i64>,
    pub copy_next: i64,
    pub cleanup_to: i64,
    pub cleanup_next: i64,
    pub failed: i64,
    #[sea_orm(
        belongs_to,
        from = "manifest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_frozen_history: HasOne<super::compaction_frozen_history::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
