//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_execution_stop")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub owner: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub turn_id: String,
    #[sea_orm(
        belongs_to,
        from = "owner",
        to = "owner",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_context: HasOne<super::compaction_context::Entity>,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
