//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_frozen_span")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub manifest_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub kind: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub start: i64,
    pub end: i64,
    #[sea_orm(column_type = "Text")]
    pub source_manifest: String,
    #[sea_orm(
        belongs_to,
        relation_enum = "CompactionFrozenHistory2",
        from = "manifest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_frozen_history_2: HasOne<super::compaction_frozen_history::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "CompactionFrozenHistory1",
        from = "source_manifest",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub compaction_frozen_history_1: HasOne<super::compaction_frozen_history::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
