//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_operation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub owner: String,
    #[sea_orm(column_type = "Text")]
    pub fingerprint: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub snapshot: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub expected_head: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub execution_turn: Option<String>,
    pub deadline_ms: i64,
    pub attempts: i64,
    pub transient_retries: i64,
    pub correction: i64,
    pub next_portion: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub outcome: Option<String>,
    #[sea_orm(has_many)]
    pub compaction_attempt_observations: HasMany<super::compaction_attempt_observation::Entity>,
    #[sea_orm(has_many)]
    pub compaction_checkpoints: HasMany<super::compaction_checkpoint::Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner",
        to = "owner",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_context: HasOne<super::compaction_context::Entity>,
    #[sea_orm(has_many)]
    pub compaction_manifests: HasMany<super::compaction_manifest::Entity>,
    #[sea_orm(has_one)]
    pub compaction_operation_projection: HasOne<super::compaction_operation_projection::Entity>,
    #[sea_orm(has_one)]
    pub compaction_runner_plan: HasOne<super::compaction_runner_plan::Entity>,
    #[sea_orm(has_one)]
    pub compaction_runner_state: HasOne<super::compaction_runner_state::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
