//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_context")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub thread_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub owner: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub head: Option<String>,
    pub format_version: i64,
    #[sea_orm(has_many)]
    pub compaction_operations: HasMany<super::compaction_operation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub thread: HasOne<super::thread::Entity>,
    #[sea_orm(has_many, via = "compaction_execution_stop")]
    pub turns: HasMany<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
