//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_operation_projection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub operation_id: String,
    #[sea_orm(column_type = "Text")]
    pub manifest_id: String,
    #[sea_orm(column_type = "Text")]
    pub identity_sha256: String,
    #[sea_orm(column_type = "Text")]
    pub imports_sha256: String,
    pub import_count: i64,
    #[sea_orm(
        belongs_to,
        from = "manifest_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub compaction_frozen_history: HasOne<super::compaction_frozen_history::Entity>,
    #[sea_orm(
        belongs_to,
        from = "operation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_operation: HasOne<super::compaction_operation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
