//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "compaction_checkpoint")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub operation_id: String,
    #[sea_orm(column_type = "Text")]
    pub owner: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub previous: Option<String>,
    pub portion: i64,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "Text")]
    pub identity_sha256: String,
    #[sea_orm(column_type = "Text")]
    pub selection: String,
    pub projection_version: i64,
    pub format_version: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(has_many)]
    pub compaction_coverages: HasMany<super::compaction_coverage::Entity>,
    #[sea_orm(
        belongs_to,
        from = "operation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub compaction_operation: HasOne<super::compaction_operation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
