//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "idx_device_active_installation")]
    pub gateway_id: String,
    #[sea_orm(unique_key = "idx_device_active_installation")]
    pub principal_id: String,
    #[sea_orm(unique_key = "idx_device_active_installation")]
    pub installation_id: Option<String>,
    pub display_name: Option<String>,
    pub client_kind: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub platform: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_version: Option<String>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_one)]
    pub auth_session: HasOne<super::auth_session::Entity>,
    #[sea_orm(
        belongs_to,
        from = "gateway_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_identity: HasOne<super::gateway_identity::Entity>,
    #[sea_orm(
        belongs_to,
        from = "principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal: HasOne<super::gateway_principal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
