//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "execution_admission_lease")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_execution_admission_lease_subject")]
    pub subject_kind: String,
    #[sea_orm(unique_key = "uq_execution_admission_lease_subject")]
    pub subject_id: String,
    pub operation_class: String,
    pub quota_bucket: String,
    pub principal_id: String,
    pub role_key: String,
    pub workspace_id: String,
    pub policy_fingerprint: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub released_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
