//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "gateway_identity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub singleton_key: i64,
    pub identity_bootstrap_version: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub auth_schema_version: i64,
    pub auth_ready_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub audit_events: HasMany<super::audit_event::Entity>,
    #[sea_orm(has_many)]
    pub auth_sessions: HasMany<super::auth_session::Entity>,
    #[sea_orm(has_many)]
    pub devices: HasMany<super::device::Entity>,
    #[sea_orm(has_one)]
    pub gateway_principal: HasOne<super::gateway_principal::Entity>,
    #[sea_orm(has_many)]
    pub invitations: HasMany<super::invitation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
