//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "gateway_principal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub gateway_id: String,
    pub kind: String,
    pub role_key: Option<String>,
    pub status: String,
    pub display_name: String,
    pub nickname: String,
    #[sea_orm(unique_key = "idx_gateway_principal_nickname")]
    pub nickname_key: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub removed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub auth_sessions: HasMany<super::auth_session::Entity>,
    #[sea_orm(has_many)]
    pub devices: HasMany<super::device::Entity>,
    #[sea_orm(
        belongs_to,
        from = "gateway_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_identity: HasOne<super::gateway_identity::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
