//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hook_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub subscription_id: String,
    pub hook_id: String,
    pub phase: String,
    pub status: String,
    pub scope_kind: Option<String>,
    pub scope_id: Option<String>,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub task_id: Option<String>,
    pub agent_id: Option<String>,
    pub actor_kind: Option<String>,
    pub actor_id: Option<String>,
    pub context_mode: Option<String>,
    pub attempt_count: i64,
    pub contribution_count: i64,
    pub diagnostic_count: i64,
    #[sea_orm(column_type = "Text")]
    pub contribution_hashes_json: String,
    #[sea_orm(column_type = "Text")]
    pub diagnostic_previews_json: String,
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message_preview: Option<String>,
    pub error_retryable: bool,
    pub error_safe_for_user: bool,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub queued_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub deadline_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
