//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hook_audit_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub hook_run_id: String,
    pub hook_run_attempt_id: Option<String>,
    pub subscription_id: String,
    pub hook_id: String,
    pub phase: String,
    pub event_kind: String,
    pub contribution_hash: Option<String>,
    pub workspace_id: Option<String>,
    pub thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub task_id: Option<String>,
    pub agent_id: Option<String>,
    pub actor_kind: Option<String>,
    pub actor_id: Option<String>,
    pub context_mode: Option<String>,
    pub safe_for_user: bool,
    #[sea_orm(column_type = "Text")]
    pub details_json: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
