//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "invitation_workspace_grant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub invitation_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub workspace_id: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "invitation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub invitation: HasOne<super::invitation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
