//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub gateway_id: String,
    pub created_by_principal_id: String,
    pub created_by_session_id: String,
    pub status: String,
    #[sea_orm(column_type = "Binary(1)", nullable, unique)]
    pub token_hash: Option<Vec<u8>>,
    pub token_format_version: i64,
    pub expires_at: DateTimeWithTimeZone,
    pub accepted_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub accepted_principal_id: Option<String>,
    pub accepted_device_id: Option<String>,
    pub accepted_session_id: Option<String>,
    pub revoke_reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub target_role_key: String,
    #[sea_orm(
        belongs_to,
        relation_enum = "AuthSession2",
        from = "accepted_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub auth_session_2: HasOne<super::auth_session::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "AuthSession1",
        from = "created_by_session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub auth_session_1: HasOne<super::auth_session::Entity>,
    #[sea_orm(
        belongs_to,
        from = "accepted_device_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub device: HasOne<super::device::Entity>,
    #[sea_orm(
        belongs_to,
        from = "gateway_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_identity: HasOne<super::gateway_identity::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "GatewayPrincipal2",
        from = "accepted_principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal_2: HasOne<super::gateway_principal::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "GatewayPrincipal1",
        from = "created_by_principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal_1: HasOne<super::gateway_principal::Entity>,
    #[sea_orm(has_many)]
    pub invitation_workspace_grants: HasMany<super::invitation_workspace_grant::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
