//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mcp_server_installation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_mcp_server_installation_scope_name")]
    pub scope_kind: String,
    #[sea_orm(unique_key = "uq_mcp_server_installation_scope_name")]
    pub scope_key: String,
    #[sea_orm(unique_key = "uq_mcp_server_installation_scope_name")]
    pub name: String,
    pub display_name: Option<String>,
    pub source_kind: String,
    #[sea_orm(column_type = "Text")]
    pub source_ref: String,
    pub transport_kind: String,
    #[sea_orm(column_type = "Text")]
    pub transport_json: String,
    #[sea_orm(column_type = "Text")]
    pub auth_json: String,
    #[sea_orm(column_type = "Text")]
    pub secret_refs_json: String,
    pub enabled: bool,
    pub allow_implicit_invocation: bool,
    pub required: bool,
    pub fingerprint: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
