//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mcp_audit_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub turn_id: Option<String>,
    pub server_installation_id: Option<String>,
    pub server_name: String,
    pub raw_tool_name: Option<String>,
    pub callable_name: Option<String>,
    pub catalog_version: Option<String>,
    pub action: String,
    pub decision: String,
    pub reason_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub details_json: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
