//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mcp_server_catalog_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub server_installation_id: String,
    pub catalog_version: String,
    #[sea_orm(column_type = "Text")]
    pub server_info_json: String,
    pub server_instructions_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub tools_json: String,
    #[sea_orm(column_type = "Text")]
    pub resources_json: String,
    #[sea_orm(column_type = "Text")]
    pub resource_templates_json: String,
    #[sea_orm(column_type = "Text")]
    pub prompts_json: String,
    pub generated_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
