//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "patch_snapshot_reservation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub thread_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub turn_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub invocation_id: String,
    pub logical_bytes: i64,
    pub physical_bytes: i64,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
