//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "principal_avatar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub principal_id: String,
    #[sea_orm(unique)]
    pub revision_id: String,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "revision_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub principal_avatar_revision: HasOne<super::principal_avatar_revision::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
