//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recovery_terminalization_outbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recovery_job_id: String,
    pub turn_id: String,
    pub item_id: String,
    pub item_type: String,
    pub recovery_status: String,
    pub attempt_number: i64,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    pub status: String,
    pub attempt_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub next_run_at: DateTimeWithTimeZone,
    pub claim_token: Option<String>,
    pub claim_expires_at: Option<DateTimeWithTimeZone>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recovery_job_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub recovery_job: HasOne<super::recovery_job::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
