//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recovery_job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub turn_id: String,
    pub item_id: String,
    pub item_type: String,
    pub source_attempt_id: Option<String>,
    pub status: String,
    pub trigger: String,
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub policy: String,
    pub error_class: Option<String>,
    pub transport_stage: Option<String>,
    pub retry_after_ms: Option<i64>,
    pub provider_attempt_number: i64,
    #[sea_orm(column_type = "Text")]
    pub policy_snapshot: String,
    pub run_count: i64,
    pub max_attempts: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub scheduled_at: DateTimeWithTimeZone,
    pub next_run_at: DateTimeWithTimeZone,
    pub claim_token: Option<String>,
    pub claimed_at: Option<DateTimeWithTimeZone>,
    pub claim_expires_at: Option<DateTimeWithTimeZone>,
    pub active_attempt_id: Option<String>,
    pub active_attempt_started_at: Option<DateTimeWithTimeZone>,
    pub resolution_pending: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub recovery_terminalization_outbox: HasOne<super::recovery_terminalization_outbox::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
