//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "skill_upload_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub upload_id: String,
    pub workspace_id: String,
    pub connection_id: i64,
    pub status: String,
    pub file_name: String,
    pub archive_format: String,
    pub compressed_size_bytes: i64,
    pub received_bytes: i64,
    pub sha256: String,
    #[sea_orm(column_type = "Text")]
    pub payload_path: String,
    pub created_at_unix: i64,
    pub expires_at_unix: i64,
    pub finalized_at_unix: Option<i64>,
    pub consumed_at_unix: Option<i64>,
    pub aborted_at_unix: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
