//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "skill_installation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub owner: Option<String>,
    pub slug: String,
    pub version: Option<String>,
    pub source_kind: String,
    pub scope_key: String,
    #[sea_orm(column_type = "Text")]
    pub source_ref: String,
    #[sea_orm(column_type = "Text")]
    pub install_path: String,
    pub trust_level: String,
    pub fingerprint: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(unique_key = "uq_skill_installation_pack_member_key")]
    pub pack_id: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "uq_skill_installation_pack_member_key"
    )]
    pub pack_member_key: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "pack_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub skill_pack_installation: HasOne<super::skill_pack_installation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
