//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_execution_admission")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: String,
    pub workspace_id: String,
    pub root_thread_id: String,
    pub initiating_principal_id: String,
    #[sea_orm(column_type = "Text")]
    pub authorization_context_json: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
