//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_delivery_authority")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub delivery_id: String,
    pub task_id: String,
    pub run_id: String,
    #[sea_orm(column_type = "Text")]
    pub author_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reviewer_json: Option<String>,
    pub destination_route_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub route_receipt_json: Option<String>,
    pub disclosure_generation: i64,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
