//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_delivery_attempt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_task_delivery_attempt_number")]
    pub delivery_id: String,
    #[sea_orm(unique_key = "uidx_task_delivery_attempt_number")]
    pub attempt_number: i64,
    pub status: String,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub http_status: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub response_fingerprint: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
