//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_occurrence_reconcile_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub task_id: String,
    pub generation: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub after_run_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub upper_run_id: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
