//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_task_run_task_number")]
    pub task_id: String,
    pub trigger_id: Option<String>,
    pub parent_run_id: Option<String>,
    pub run_group_id: String,
    pub attempt_number: i64,
    pub retry_of_run_id: Option<String>,
    pub ready_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "uidx_task_run_task_number")]
    pub run_number: i64,
    pub status: String,
    pub executor_kind: String,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    pub locked_by: Option<String>,
    pub lock_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
