//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_run_turn")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub task_id: String,
    #[sea_orm(unique_key = "uidx_task_run_turn_run_sequence")]
    pub run_id: String,
    pub execution_id: Option<String>,
    pub thread_id: String,
    #[sea_orm(unique)]
    pub turn_id: String,
    pub kind: String,
    #[sea_orm(unique_key = "uidx_task_run_turn_candidate_round")]
    pub round: i64,
    #[sea_orm(unique_key = "uidx_task_run_turn_run_sequence")]
    pub sequence: i64,
    pub status: String,
    pub reviews_candidate_id: Option<String>,
    pub requested_by_candidate_id: Option<String>,
    pub requested_by_review_event_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
