//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub owner_kind: String,
    pub owner_id: Option<String>,
    pub created_by_thread_id: Option<String>,
    pub created_by_turn_id: Option<String>,
    pub root_task_id: Option<String>,
    pub parent_task_id: Option<String>,
    pub executor_kind: String,
    pub status: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub goal: String,
    pub priority: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub lifecycle_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub delivery_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub retry_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timeout_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub concurrency_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_json: Option<String>,
    pub revision: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
