//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_occurrence_contract")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub occurrence_id: String,
    #[sea_orm(unique_key = "idx_task_occurrence_generation")]
    pub task_id: String,
    #[sea_orm(unique)]
    pub run_id: String,
    pub trigger_id: Option<String>,
    pub occurrence_key: String,
    #[sea_orm(unique_key = "idx_task_occurrence_generation")]
    pub execution_generation: i64,
    pub agent_execution_id: Option<String>,
    pub work_graph_root_execution_id: Option<String>,
    pub root_resource_scope_id: Option<String>,
    pub status: String,
    pub queue_position: Option<i64>,
    pub retry_attempt: i64,
    #[sea_orm(unique)]
    pub action_idempotency_key: String,
    pub route_id: Option<String>,
    pub result_return_route_id: Option<String>,
    pub terminal_reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
