//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_agent_spec")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub task_id: String,
    pub run_id: Option<String>,
    pub agent_role: Option<String>,
    pub agent_nickname: Option<String>,
    pub model: Option<String>,
    pub model_provider: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub prompt_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub context_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tool_policy_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_contract_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub review_policy_json: Option<String>,
    pub depth: i64,
    pub max_depth: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub permission_cap_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub security_cap_json: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
