//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_dependency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_task_dependency_pair_kind")]
    pub task_id: String,
    #[sea_orm(unique_key = "uidx_task_dependency_pair_kind")]
    pub depends_on_task_id: String,
    #[sea_orm(unique_key = "uidx_task_dependency_pair_kind")]
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub condition_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
