//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_delivery")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub task_id: String,
    pub run_id: String,
    #[sea_orm(unique)]
    pub delivery_key: String,
    pub mode: String,
    pub thread_target: Option<String>,
    pub target_thread_id: Option<String>,
    pub target_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub webhook_url: Option<String>,
    pub webhook_url_fingerprint: Option<String>,
    pub status: String,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    pub attempt_count: i64,
    pub max_attempts: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_snapshot_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_snapshot_json: Option<String>,
    pub delivered_turn_id: Option<String>,
    pub delivered_notification_id: Option<String>,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub user_notification_outbox: HasOne<super::user_notification_outbox::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
