//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_thread_directory")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub thread_id: String,
    pub title: Option<String>,
    pub summary_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary_ref: Option<String>,
    pub thread_created_at: Option<DateTimeWithTimeZone>,
    pub thread_updated_at: Option<DateTimeWithTimeZone>,
    pub last_indexed_at: Option<DateTimeWithTimeZone>,
    pub indexed_chunk_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub task_affinity_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_affinity_json: Option<String>,
    pub visibility: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
