//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_lineage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_thread_id: String,
    pub parent_thread_id: String,
    pub root_thread_id: String,
    pub depth: i64,
    pub created_at: DateTimeWithTimeZone,
    pub origin_kind: Option<String>,
    pub created_by_thread_id: Option<String>,
    pub created_by_turn_id: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
