//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_cli_runtime_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub thread_id: String,
    pub workspace_id: String,
    pub runtime_id: String,
    pub runtime_kind: String,
    #[sea_orm(column_type = "Text")]
    pub native_thread_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_session_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_root_thread_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_cwd: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_model: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub resume_cursor_json: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_adapter_kind: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_manifest_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_projection_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_provider_contract_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_isolation_contract_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_session_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_session_lifecycle_state: Option<String>,
    pub mcp_session_generation: Option<i64>,
    pub provider_session_last_verified_process_generation: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
