//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_exclusions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_exclusions_chunk")]
    pub workspace_id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_exclusions_chunk")]
    pub thread_id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_exclusions_chunk")]
    pub chunk_id: String,
    pub reason: String,
    pub created_by: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
