//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_recall_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub thread_id: String,
    pub turn_id: String,
    pub query_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub search_profile_json: Option<String>,
    pub search_mode: Option<String>,
    pub adaptive_strategy: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cutoff_json: Option<String>,
    pub candidate_count: i64,
    pub returned_count: i64,
    pub latency_ms: i64,
    pub fallback_used: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
