//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_agents_doc")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub workspace_id: String,
    #[sea_orm(unique_key = "uq_thread_agents_doc_folder_active")]
    pub folder_id: Option<String>,
    pub status: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub content_sha256: String,
    pub version: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub archived_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<String>,
    pub updated_by: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
