//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_capsules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_capsules_segment")]
    pub workspace_id: String,
    pub workspace_key_hash: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_capsules_segment")]
    pub thread_id: String,
    pub thread_key_hash: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_capsules_segment")]
    pub segment_index: i64,
    pub write_state: String,
    #[sea_orm(column_type = "Text", unique)]
    pub capsule_ref: String,
    #[sea_orm(column_type = "Text")]
    pub storage_uri: String,
    pub backend: String,
    pub format: String,
    pub encrypted: bool,
    pub status: String,
    pub repair_status: String,
    pub active_frame_count: i64,
    pub capacity_bytes: Option<i64>,
    pub size_bytes: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub utilization_percent: Option<f64>,
    pub last_capacity_check_at: Option<DateTimeWithTimeZone>,
    pub near_capacity_at: Option<DateTimeWithTimeZone>,
    pub capacity_exceeded_at: Option<DateTimeWithTimeZone>,
    pub last_vacuumed_at: Option<DateTimeWithTimeZone>,
    pub last_compacted_at: Option<DateTimeWithTimeZone>,
    pub content_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
