//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_embedding_artifacts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub pipeline_identity_hash: String,
    pub input_hash: String,
    pub provider_id: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    pub dimension: i64,
    pub normalized: bool,
    #[sea_orm(column_type = "Binary(1)")]
    pub vector_bytes: Vec<u8>,
    pub created_at: DateTimeWithTimeZone,
    pub last_used_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
