//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_episodic_index_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub thread_id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_index_jobs_item_capsule")]
    pub index_item_id: String,
    #[sea_orm(unique_key = "uidx_thread_episodic_index_jobs_item_capsule")]
    pub capsule_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub capsule_ref: Option<String>,
    pub segment_index: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub frame_uri: Option<String>,
    pub status: String,
    pub graph_enrichment_state: String,
    pub attempt_count: i64,
    pub capacity_error_count: i64,
    pub last_attempt_latency_ms: Option<i64>,
    pub next_run_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
