//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub preview: String,
    pub mode: String,
    pub model: String,
    pub model_provider: String,
    pub status: String,
    pub origin_kind: String,
    pub sidebar_visibility: String,
    pub agent_nickname: Option<String>,
    pub agent_role: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub summary_turn_count: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by_actor_id: Option<String>,
    pub created_by_actor_kind: Option<String>,
    pub access_class: String,
    #[sea_orm(has_many, via = "thread_membership")]
    pub gateway_principals: HasMany<super::gateway_principal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
