//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_agents_doc_revision")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_thread_agents_doc_revision_doc_version")]
    pub doc_id: String,
    #[sea_orm(unique_key = "uq_thread_agents_doc_revision_doc_version")]
    pub version: i64,
    pub content_sha256: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub saved_at: DateTimeWithTimeZone,
    pub saved_by: Option<String>,
    pub save_reason: String,
}

impl ActiveModelBehavior for ActiveModel {}
