//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_read_cursor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub principal_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub thread_id: String,
    pub last_read_sort_key: String,
    pub last_read_turn_id: String,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "principal_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub gateway_principal: HasOne<super::gateway_principal::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub thread: HasOne<super::thread::Entity>,
    #[sea_orm(
        belongs_to,
        from = "last_read_turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
