//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tool_output_chunk")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub ordinal: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub turn_id: String,
    #[sea_orm(column_type = "Text")]
    pub item_id: String,
    #[sea_orm(column_type = "Text")]
    pub stream: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
