//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_execution_window")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workspace_id: String,
    pub thread_id: String,
    #[sea_orm(unique_key = "uidx_turn_execution_window_turn_index")]
    pub turn_id: String,
    #[sea_orm(unique_key = "uidx_turn_execution_window_turn_index")]
    pub window_index: i64,
    pub status: String,
    pub exhaustion_reason: Option<String>,
    pub agent_round_count: i64,
    pub tool_call_count: i64,
    pub provider_token_count: i64,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
