//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_runtime_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub turn_id: String,
    pub thread_id: String,
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub mode_json: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub provider_name: String,
    #[sea_orm(column_type = "Text")]
    pub hook_runtime_context_json: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_skill_policies_json: String,
    #[sea_orm(column_type = "Text")]
    pub input_json: String,
    #[sea_orm(column_type = "Text")]
    pub capabilities_json: String,
    #[sea_orm(column_type = "Text")]
    pub resolved_artifacts_json: String,
    #[sea_orm(column_type = "Text")]
    pub runtime_environment_json: String,
    #[sea_orm(column_type = "Text")]
    pub history_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
