//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub thread_id: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub prompt_manifest_json: String,
    pub prompt_compiler_version: Option<String>,
    pub prompt_profile: Option<String>,
    pub prompt_fingerprint_stable: Option<String>,
    pub prompt_fingerprint_dynamic: Option<String>,
    pub prompt_fingerprint_full: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub turn_kind: String,
    pub origin: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reasoning_effort: Option<String>,
    pub permission_profile_mode: Option<String>,
    pub permission_profile_source: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub permission_profile_snapshot_json: Option<String>,
    pub execution_security_snapshot_version: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub execution_security_snapshot_json: Option<String>,
    pub initiated_by_actor_id: Option<String>,
    pub initiated_by_actor_kind: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub execution_authorization_context_json: Option<String>,
    pub send_mode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub author_display_name_snapshot: Option<String>,
    pub author_nickname_snapshot: Option<String>,
    pub author_avatar_revision_snapshot: Option<String>,
    pub reply_to_turn_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub mentions_json: String,
    pub message_revision: i64,
    pub message_deleted_at: Option<DateTimeWithTimeZone>,
    pub message_deleted_by_actor_id: Option<String>,
    pub message_deleted_by_actor_kind: Option<String>,
    #[sea_orm(has_many)]
    pub thread_read_cursors: HasMany<super::thread_read_cursor::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "reply_to_turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub turn: HasOne<Entity>,
    #[sea_orm(has_one)]
    pub turn_cli_runtime_instruction: HasOne<super::turn_cli_runtime_instruction::Entity>,
    #[sea_orm(has_one)]
    pub turn_mcp_projection: HasOne<super::turn_mcp_projection::Entity>,
    #[sea_orm(has_many)]
    pub turn_message_revisions: HasMany<super::turn_message_revision::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
