//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_cli_runtime_execution_segment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uidx_turn_cli_runtime_execution_segment_attempt_index")]
    pub attempt_id: String,
    pub turn_id: String,
    #[sea_orm(unique_key = "uidx_turn_cli_runtime_execution_segment_attempt_index")]
    pub segment_index: i64,
    #[sea_orm(unique_key = "uidx_turn_cli_runtime_execution_segment_runtime_native_turn")]
    pub runtime_id: String,
    #[sea_orm(column_type = "Text")]
    pub native_thread_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "uidx_turn_cli_runtime_execution_segment_runtime_native_turn"
    )]
    pub native_turn_id: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_reason: Option<String>,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
