//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_mcp_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_mcp_binding_turn_callable")]
    pub turn_id: String,
    pub server_installation_id: String,
    pub server_name: String,
    pub raw_tool_name: String,
    #[sea_orm(unique_key = "uq_turn_mcp_binding_turn_callable")]
    pub callable_name: String,
    pub catalog_version: String,
    pub fingerprint: String,
    pub created_at: DateTimeWithTimeZone,
    pub selection_reason: String,
    pub capability_id: Option<String>,
    pub canonical_callable_name: String,
    pub provider_callable_name: String,
    pub canonical_schema_fingerprint: String,
    pub provider_schema_fingerprint: String,
    #[sea_orm(column_type = "Text")]
    pub annotations_json: String,
    pub annotations_digest: String,
    pub effective_timeout_ms: i64,
    pub runtime_generation: i64,
    pub projection_activation_generation: i64,
}

impl ActiveModelBehavior for ActiveModel {}
