//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_llm_context")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_llm_context_turn_id_sequence")]
    pub turn_id: String,
    pub item_id: Option<String>,
    pub attempt_id: Option<String>,
    #[sea_orm(unique_key = "uq_turn_llm_context_turn_id_sequence")]
    pub sequence: i64,
    pub source: String,
    pub tool_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    #[sea_orm(column_type = "Text")]
    pub output_policy_snapshot: String,
    pub delivery_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
