//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_skill_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_skill_binding_turn_id_skill_id")]
    pub turn_id: String,
    #[sea_orm(unique_key = "uq_turn_skill_binding_turn_id_skill_id")]
    pub skill_id: String,
    pub skill_owner: Option<String>,
    pub skill_slug: String,
    pub skill_version: Option<String>,
    pub fingerprint: String,
    pub source_kind: String,
    pub resolved_reason: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
