//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub thread_id: String,
    #[sea_orm(unique_key = "idx_turn_events_turn_id_sequence")]
    pub turn_id: String,
    #[sea_orm(unique_key = "idx_turn_events_turn_id_sequence")]
    pub sequence: i64,
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(unique_key = "uq_turn_event_turn_id_idempotency_key")]
    pub idempotency_key: Option<String>,
    #[sea_orm(has_many)]
    pub turn_event_deliveries: HasMany<super::turn_event_delivery::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
