//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_cli_runtime_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub turn_id: String,
    pub thread_id: String,
    pub workspace_id: String,
    pub runtime_id: String,
    pub runtime_kind: String,
    #[sea_orm(column_type = "Text")]
    pub native_thread_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_turn_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_id: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cwd: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sandbox_json: Option<String>,
    pub approval_policy: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub input_mapping_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_adapter_kind: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_manifest_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_projection_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_provider_contract_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mcp_isolation_contract_fingerprint: Option<String>,
    pub mcp_session_generation: Option<i64>,
    pub mcp_projection_activation_generation: Option<i64>,
    pub native_goal_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub native_goal_turn_id: Option<String>,
    pub native_goal_observed_at: Option<DateTimeWithTimeZone>,
    pub continuation_thread_id: String,
}

impl ActiveModelBehavior for ActiveModel {}
