//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_item_attempt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_item_attempt_turn_item_attempt_number")]
    pub turn_id: String,
    #[sea_orm(unique_key = "uq_turn_item_attempt_turn_item_attempt_number")]
    pub item_id: String,
    pub item_type: String,
    #[sea_orm(unique_key = "uq_turn_item_attempt_turn_item_attempt_number")]
    pub attempt_number: i64,
    pub status: String,
    pub timeout_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_reason: Option<String>,
    pub recovery_action: Option<String>,
    pub idempotency_key: Option<String>,
    pub trace_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub started_at: DateTimeWithTimeZone,
    pub last_heartbeat_at: Option<DateTimeWithTimeZone>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub idle_deadline_at: Option<DateTimeWithTimeZone>,
    pub hard_deadline_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub started_event_sequence: Option<i64>,
    pub recovery_suppressed_reason: Option<String>,
    pub recovery_suppressed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recovery_suppression_context_json: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
