//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_execution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub turn_id: String,
    pub thread_id: String,
    pub workspace_id: String,
    pub executor_kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub executor_key: Option<String>,
    pub status: String,
    pub owner_id: String,
    pub owner_generation: i64,
    pub lease_until: DateTimeWithTimeZone,
    pub heartbeat_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
