//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub thread_id: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub prompt_manifest_json: String,
    pub prompt_compiler_version: Option<String>,
    pub prompt_profile: Option<String>,
    pub prompt_fingerprint_stable: Option<String>,
    pub prompt_fingerprint_dynamic: Option<String>,
    pub prompt_fingerprint_full: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub turn_kind: String,
    pub origin: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reasoning_effort: Option<String>,
    pub permission_profile_mode: Option<String>,
    pub permission_profile_source: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub permission_profile_snapshot_json: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
