//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_input")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_input_turn_id_input_index")]
    pub turn_id: String,
    #[sea_orm(unique_key = "uq_turn_input_turn_id_input_index")]
    pub input_index: i64,
    pub input_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub text: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
