//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_admission")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "idx_turn_admission_scope"
    )]
    pub turn_id: String,
    #[sea_orm(unique_key = "idx_turn_admission_scope")]
    pub thread_id: String,
    #[sea_orm(unique_key = "idx_turn_admission_scope")]
    pub workspace_id: String,
    pub request_digest: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "turn_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub turn: HasOne<super::turn::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
