//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_work_projection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub turn_id: String,
    pub workspace_id: String,
    pub thread_id: String,
    pub presentation: String,
    pub state: String,
    pub work_count: i64,
    pub visible_work_count: i64,
    pub hidden_work_count: i64,
    pub first_work_item_id: Option<String>,
    pub last_work_item_id: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub elapsed_ms: Option<i64>,
    pub source_high_watermark: i64,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
