//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_item_turn_id_item_id")]
    pub turn_id: String,
    #[sea_orm(unique_key = "uq_turn_item_turn_id_item_id")]
    pub item_id: String,
    pub item_type: String,
    pub status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub active_attempt_number: i64,
    pub active_attempt_status: Option<String>,
    pub active_attempt_id: Option<String>,
    pub last_heartbeat_at: Option<DateTimeWithTimeZone>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub agent_action_timeline_target: HasOne<super::agent_action_timeline_target::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
