//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub thread_id: String,
    #[sea_orm(unique_key = "idx_turn_events_turn_id_sequence")]
    pub turn_id: String,
    #[sea_orm(unique_key = "idx_turn_events_turn_id_sequence")]
    pub sequence: i64,
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub idempotency_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
