//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "turn_mcp_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "uq_turn_mcp_binding_turn_callable")]
    pub turn_id: String,
    pub server_installation_id: String,
    pub server_name: String,
    pub raw_tool_name: String,
    #[sea_orm(unique_key = "uq_turn_mcp_binding_turn_callable")]
    pub callable_name: String,
    pub catalog_version: String,
    pub fingerprint: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
