//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_notification_outbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub task_delivery_id: String,
    pub workspace_id: String,
    pub recipient_principal_id: String,
    pub task_id: String,
    pub run_id: String,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub delivered_at: DateTimeWithTimeZone,
    pub acknowledged_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "task_delivery_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub task_delivery: HasOne<super::task_delivery::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
