//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub is_active: bool,
    #[sea_orm(unique)]
    pub is_current: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub actor_nickname_indices: HasMany<super::actor_nickname_index::Entity>,
    #[sea_orm(has_many)]
    pub agent_executions: HasMany<super::agent_execution::Entity>,
    #[sea_orm(has_many)]
    pub agent_identities: HasMany<super::agent_identity::Entity>,
    #[sea_orm(has_many)]
    pub agent_skills: HasMany<super::agent_skill::Entity>,
    #[sea_orm(has_many)]
    pub native_agent_configs: HasMany<super::native_agent_config::Entity>,
    #[sea_orm(has_many)]
    pub self_improvement_runs: HasMany<super::self_improvement_run::Entity>,
    #[sea_orm(has_many)]
    pub self_improvement_source_turns: HasMany<super::self_improvement_source_turn::Entity>,
    #[sea_orm(has_one)]
    pub self_improvement_workspace_state: HasOne<super::self_improvement_workspace_state::Entity>,
    #[sea_orm(has_many, via = "workspace_membership")]
    pub gateway_principals: HasMany<super::gateway_principal::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
