[package]
name = "pioneer-desktop-plugins"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui-kit = { workspace = true, features = ["component"] }
pioneer-client.workspace = true
rust-i18n.workspace = true
pioneer-desktop-foundation.workspace = true
tokio.workspace = true
pioneer-protocol.workspace = true
pioneer-desktop-mcp.workspace = true
pioneer-desktop-skills.workspace = true
