//! Safe CLI runtime provider diagnostics export.

use pioneer_protocol::{
    CLIAgentRuntimeKind, RuntimeDiagnostic, RuntimeStatus, RuntimeSummary,
    sanitize_runtime_diagnostic_line, sanitize_runtime_diagnostic_lines,
};

#[cfg_attr(any(feature = "schema", test), derive(schemars::JsonSchema))]
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct CLIRuntimeProviderDiagnosticsBundle {
    pub schema_version: u32,
    pub runtime_id: String,
    pub kind: CLIAgentRuntimeKind,
    pub display_name: String,
    pub enabled: bool,
    pub status: RuntimeStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub binary_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub home_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shadow_home_path: Option<String>,
    #[serde(default)]
    pub debug_native_events_enabled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub models_refreshed_at_unix_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<RuntimeDiagnostic>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub recent_stderr: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<String>,
}

pub fn cli_runtime_provider_diagnostics_bundle(
    runtime: &RuntimeSummary,
) -> CLIRuntimeProviderDiagnosticsBundle {
    let diagnostics = runtime
        .diagnostics
        .iter()
        .map(|diagnostic| RuntimeDiagnostic {
            level: diagnostic.level,
            code: sanitize_runtime_diagnostic_line(diagnostic.code.as_str()),
            message: sanitize_runtime_diagnostic_line(diagnostic.message.as_str()),
        })
        .collect();
    let mut notes = vec![
        "Generated by Pioneer Desktop CLI provider diagnostics.".to_owned(),
        "Secret-like values and large diagnostic lines are redacted or truncated.".to_owned(),
    ];
    if runtime.debug_native_events_enabled {
        notes.push(
            "Native event diagnostics are enabled; only redacted native payloads should be shared."
                .to_owned(),
        );
    }

    CLIRuntimeProviderDiagnosticsBundle {
        schema_version: 1,
        runtime_id: runtime.runtime_id.clone(),
        kind: runtime.kind,
        display_name: runtime.display_name.clone(),
        enabled: runtime.enabled,
        status: runtime.status.clone(),
        version: runtime.version.clone(),
        binary_path: runtime.binary_path.clone(),
        home_path: runtime.home_path.clone(),
        shadow_home_path: runtime.shadow_home_path.clone(),
        debug_native_events_enabled: runtime.debug_native_events_enabled,
        models_refreshed_at_unix_ms: runtime.models_refreshed_at_unix_ms,
        diagnostics,
        recent_stderr: sanitize_runtime_diagnostic_lines(runtime.recent_stderr.clone()),
        notes,
    }
}

pub fn cli_runtime_provider_diagnostics_json(runtime: &RuntimeSummary) -> String {
    serde_json::to_string_pretty(&cli_runtime_provider_diagnostics_bundle(runtime)).unwrap_or_else(
        |error| format!("{{\"error\":\"diagnostics serialization failed: {error}\"}}"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use pioneer_protocol::{
        RUNTIME_DIAGNOSTIC_MAX_LINES, RuntimeCapabilities, RuntimeDiagnosticLevel,
    };

    fn runtime_summary() -> RuntimeSummary {
        RuntimeSummary {
            runtime_id: "codex_personal".to_owned(),
            kind: CLIAgentRuntimeKind::Codex,
            display_name: "Codex Personal".to_owned(),
            enabled: true,
            status: RuntimeStatus::Ready,
            capabilities: RuntimeCapabilities::default(),
            account: None,
            version: Some("1.2.3".to_owned()),
            binary_path: Some("codex".to_owned()),
            home_path: Some("~/.codex".to_owned()),
            shadow_home_path: Some("~/.pioneer/codex/personal".to_owned()),
            debug_native_events_enabled: true,
            models_refreshed_at_unix_ms: None,
            diagnostics: Vec::new(),
            recent_stderr: Vec::new(),
        }
    }

    #[test]
    fn cli_runtime_provider_diagnostics_redacts_tokens_headers_and_raw_blobs() {
        let mut runtime = runtime_summary();
        runtime.diagnostics = vec![RuntimeDiagnostic {
            level: RuntimeDiagnosticLevel::Error,
            code: "codex_probe.raw".to_owned(),
            message:
                "headers={Authorization: Bearer sk-secret} apiToken=\"secret\" raw={very-secret}"
                    .to_owned(),
        }];
        runtime.recent_stderr = vec![
            "OPENAI_API_KEY=sk-secret Authorization: Bearer sk-proj-secret".to_owned(),
            format!("stderr {}", "x".repeat(900)),
        ];

        let json = cli_runtime_provider_diagnostics_json(&runtime);

        assert!(json.contains("[REDACTED]"));
        assert!(!json.contains("sk-secret"));
        assert!(!json.contains("sk-proj-secret"));
        assert!(!json.contains("very-secret"));
        assert!(json.contains("[truncated "));
        assert!(json.contains("Native event diagnostics are enabled"));
    }

    #[test]
    fn cli_runtime_provider_diagnostics_bounds_stderr_lines() {
        let mut runtime = runtime_summary();
        runtime.recent_stderr = (0..(RUNTIME_DIAGNOSTIC_MAX_LINES + 3))
            .map(|index| format!("line {index}"))
            .collect();

        let bundle = cli_runtime_provider_diagnostics_bundle(&runtime);

        assert_eq!(bundle.recent_stderr.len(), RUNTIME_DIAGNOSTIC_MAX_LINES);
        assert_eq!(bundle.recent_stderr[0], "line 3");
    }
}
