mod administration;
mod bottom_bar;
mod conversation;
mod editor;
mod file_openers;
mod flow;
mod gateway_setup;
mod initial;
mod invitation_join;
mod mcp;
mod member_avatars;
mod providers;
mod root;
mod settings;
mod sidebar;
mod skills;
mod startup;
mod task_notifications;
mod thread;

pub(crate) use root::LegacyScreenAdapter as PioneerDesktop;
pub(crate) use root::{FrameChanged, LegacyScreenAdapter, SidebarChanged};
