//! Schema and contract export helpers.

use std::any::type_name;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ClientContractDomain {
    Root,
    Connection,
    Timeline,
    Composer,
    Artifacts,
    Providers,
    Skills,
    Mcp,
    Settings,
    Tasks,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ClientContractKind {
    Snapshot,
    Event,
    Command,
    Effect,
    SelectorDto,
    PresentationDto,
    ActionState,
    ActionPlan,
    RegistryDto,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ClientContractStability {
    Stable,
    Provisional,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ClientContractType {
    pub file_name: &'static str,
    pub rust_type: &'static str,
    pub domain: ClientContractDomain,
    pub kind: ClientContractKind,
    pub stability: ClientContractStability,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ClientSchemaInternalExclusion {
    pub rust_type: &'static str,
    pub reason: &'static str,
}

macro_rules! contract_type {
    ($file_name:literal, $ty:ty, $domain:expr, $kind:expr, $stability:expr) => {
        ClientContractType {
            file_name: $file_name,
            rust_type: type_name::<$ty>(),
            domain: $domain,
            kind: $kind,
            stability: $stability,
        }
    };
}

macro_rules! internal_exclusion {
    ($ty:ty, $reason:literal) => {
        ClientSchemaInternalExclusion {
            rust_type: type_name::<$ty>(),
            reason: $reason,
        }
    };
}

pub fn client_contract_types() -> Vec<ClientContractType> {
    use ClientContractDomain as Domain;
    use ClientContractKind as Kind;
    use ClientContractStability as Stability;

    let mut contracts = vec![
        contract_type!(
            "active_thread_phase_snapshot.json",
            crate::state::snapshot::ActiveThreadPhaseSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "active_thread_snapshot.json",
            crate::state::snapshot::ActiveThreadSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "active_thread_status_snapshot.json",
            crate::state::snapshot::ActiveThreadStatusSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "activate_gateway_registry_plan.json",
            crate::gateway::setup::ActivateGatewayRegistryPlan,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "agent_execution_backend.json",
            pioneer_protocol::AgentExecutionBackend,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_action_status.json",
            crate::artifacts::actions::ArtifactActionStatus,
            Domain::Artifacts,
            Kind::ActionState,
            Stability::Stable
        ),
        contract_type!(
            "artifact_download_request_plan_error.json",
            crate::artifacts::actions::ArtifactDownloadRequestPlanError,
            Domain::Artifacts,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_download_request.json",
            crate::artifacts::download::ArtifactDownloadRequest,
            Domain::Artifacts,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_download_result.json",
            crate::artifacts::download::ArtifactDownloadResult,
            Domain::Artifacts,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_file_action_block_reason.json",
            crate::artifacts::actions::ArtifactFileActionBlockReason,
            Domain::Artifacts,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_upload_file_request.json",
            crate::artifacts::upload::ArtifactUploadFileRequest,
            Domain::Artifacts,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "artifact_version_key.json",
            crate::artifacts::actions::ArtifactVersionKey,
            Domain::Artifacts,
            Kind::ActionState,
            Stability::Stable
        ),
        contract_type!(
            "capability_rejection_row.json",
            crate::timeline::labels::CapabilityRejectionRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "cli_agent_runtime_kind.json",
            pioneer_protocol::CLIAgentRuntimeKind,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_agent_runtime_sandbox_policy.json",
            pioneer_protocol::CLIAgentRuntimeSandboxPolicy,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_account_updated_notification.json",
            pioneer_protocol::CLIRuntimeAccountUpdatedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_apps_changed_notification.json",
            pioneer_protocol::CLIRuntimeAppsChangedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_get_params.json",
            pioneer_protocol::CLIRuntimeGetParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_get_response.json",
            pioneer_protocol::CLIRuntimeGetResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_list_models_params.json",
            pioneer_protocol::CLIRuntimeListModelsParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_list_models_response.json",
            pioneer_protocol::CLIRuntimeListModelsResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_login_start_type.json",
            pioneer_protocol::CLIRuntimeLoginStartType,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_login_start_params.json",
            pioneer_protocol::CLIRuntimeLoginStartParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_login_start_response.json",
            pioneer_protocol::CLIRuntimeLoginStartResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_login_cancel_params.json",
            pioneer_protocol::CLIRuntimeLoginCancelParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_login_cancel_response.json",
            pioneer_protocol::CLIRuntimeLoginCancelResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_list_params.json",
            pioneer_protocol::CLIRuntimeListParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_list_response.json",
            pioneer_protocol::CLIRuntimeListResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_binding_get_params.json",
            pioneer_protocol::CLIRuntimeThreadBindingGetParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_binding_get_response.json",
            pioneer_protocol::CLIRuntimeThreadBindingGetResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_binding.json",
            pioneer_protocol::CLIRuntimeThreadBinding,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_compact_params.json",
            pioneer_protocol::CLIRuntimeThreadCompactParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_compact_response.json",
            pioneer_protocol::CLIRuntimeThreadCompactResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_fork_params.json",
            pioneer_protocol::CLIRuntimeThreadForkParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_thread_fork_response.json",
            pioneer_protocol::CLIRuntimeThreadForkResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_turn_steer_params.json",
            pioneer_protocol::CLIRuntimeTurnSteerParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_turn_steer_response.json",
            pioneer_protocol::CLIRuntimeTurnSteerResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_review_delivery.json",
            pioneer_protocol::CLIRuntimeReviewDelivery,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_review_target.json",
            pioneer_protocol::CLIRuntimeReviewTarget,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_review_start_params.json",
            pioneer_protocol::CLIRuntimeReviewStartParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_review_start_response.json",
            pioneer_protocol::CLIRuntimeReviewStartResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_pending_request.json",
            pioneer_protocol::CLIRuntimePendingRequest,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_pending_request_status.json",
            pioneer_protocol::CLIRuntimePendingRequestStatus,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_kind.json",
            pioneer_protocol::CLIRuntimeRequestKind,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_opened_notification.json",
            pioneer_protocol::CLIRuntimeRequestOpenedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_resolution.json",
            pioneer_protocol::CLIRuntimeRequestResolution,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_resolved_notification.json",
            pioneer_protocol::CLIRuntimeRequestResolvedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_respond_params.json",
            pioneer_protocol::CLIRuntimeRequestRespondParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_request_respond_response.json",
            pioneer_protocol::CLIRuntimeRequestRespondResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request.json",
            crate::cli_runtime::approvals::PendingRequest,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_kind.json",
            crate::cli_runtime::approvals::PendingRequestKind,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_origin.json",
            crate::cli_runtime::approvals::PendingRequestOrigin,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_payload.json",
            crate::cli_runtime::approvals::PendingRequestPayload,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_resolution.json",
            crate::cli_runtime::approvals::PendingRequestResolution,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_action_kind.json",
            crate::cli_runtime::approvals::PendingRequestActionKind,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_available_action.json",
            crate::cli_runtime::approvals::PendingRequestAvailableAction,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_detail_row.json",
            crate::cli_runtime::approvals::PendingRequestDetailRow,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_detail_style.json",
            crate::cli_runtime::approvals::PendingRequestDetailStyle,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_presentation.json",
            crate::cli_runtime::approvals::PendingRequestPresentation,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_user_input_option.json",
            crate::cli_runtime::approvals::PendingRequestUserInputOption,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "pending_request_user_input_question.json",
            crate::cli_runtime::approvals::PendingRequestUserInputQuestion,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_approval_request.json",
            pioneer_protocol::TurnPermissionApprovalRequest,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_approval_request_detail.json",
            pioneer_protocol::TurnPermissionApprovalRequestDetail,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_approval_resolution.json",
            pioneer_protocol::TurnPermissionApprovalResolution,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_request_opened_notification.json",
            pioneer_protocol::TurnPermissionRequestOpenedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_request_resolved_notification.json",
            pioneer_protocol::TurnPermissionRequestResolvedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_request_respond_params.json",
            pioneer_protocol::TurnPermissionRequestRespondParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "turn_permission_request_respond_response.json",
            pioneer_protocol::TurnPermissionRequestRespondResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_refresh_params.json",
            pioneer_protocol::CLIRuntimeRefreshParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_refresh_response.json",
            pioneer_protocol::CLIRuntimeRefreshResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_status_changed_notification.json",
            pioneer_protocol::CLIRuntimeStatusChangedNotification,
            Domain::Providers,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_status_params.json",
            pioneer_protocol::CLIRuntimeStatusParams,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_status_response.json",
            pioneer_protocol::CLIRuntimeStatusResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "client_effect.json",
            crate::notifications::effects::ClientEffect,
            Domain::Root,
            Kind::Effect,
            Stability::Stable
        ),
        contract_type!(
            "client_snapshot.json",
            crate::state::snapshot::ClientSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "client_security_diagnostic.json",
            crate::security::ClientSecurityDiagnostic,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "client_security_diagnostic_row.json",
            crate::security::ClientSecurityDiagnosticRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "client_security_enforcement_status.json",
            crate::security::ClientSecurityEnforcementStatus,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "client_security_filesystem_access.json",
            crate::security::ClientSecurityFilesystemAccess,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "client_turn_security_summary.json",
            crate::security::ClientTurnSecuritySummary,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_attachment.json",
            crate::composer::attachments::ComposerAttachment,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_attachment_kind.json",
            crate::composer::attachments::ComposerAttachmentKind,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_attachment_upload_state.json",
            crate::composer::attachments::ComposerAttachmentUploadState,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_capability.json",
            crate::composer::capabilities::ComposerCapability,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_capability_kind.json",
            crate::composer::capabilities::ComposerCapabilityKind,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_draft.json",
            crate::composer::draft::ComposerDraft<
                crate::composer::attachments::ComposerAttachment,
                crate::composer::capabilities::ComposerCapability,
            >,
            Domain::Composer,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "composer_permission_mode_option.json",
            crate::composer::permissions::ComposerPermissionModeOption,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_model_selection.json",
            crate::composer::model_selection::ComposerModelSelection,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_model_selection_state.json",
            crate::composer::model_selection::ComposerModelSelectionState,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "composer_model_selection_candidate.json",
            crate::composer::model_selection::ComposerModelSelectionCandidate,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "gateway_connection_state.json",
            crate::state::client_state::GatewayConnectionState,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_endpoint.json",
            crate::gateway::types::GatewayEndpoint,
            Domain::Connection,
            Kind::RegistryDto,
            Stability::Stable
        ),
        contract_type!(
            "gateway_endpoint_kind.json",
            crate::gateway::types::GatewayEndpointKind,
            Domain::Connection,
            Kind::RegistryDto,
            Stability::Stable
        ),
        contract_type!(
            "gateway_registry.json",
            crate::gateway::types::GatewayRegistry,
            Domain::Connection,
            Kind::RegistryDto,
            Stability::Stable
        ),
        contract_type!(
            "gateway_auth_token_write.json",
            crate::gateway::setup::GatewayAuthTokenWrite,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "set_gateway_workspace_registry_plan.json",
            crate::gateway::setup::SetGatewayWorkspaceRegistryPlan,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "gateway_remote_access_status_label.json",
            crate::settings::gateway::GatewayRemoteAccessStatusLabel,
            Domain::Settings,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_settings_state.json",
            crate::settings::gateway::GatewaySettingsState,
            Domain::Settings,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_settings_action_scope.json",
            crate::settings::gateway::GatewaySettingsActionScope,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "gateway_settings_refresh_plan.json",
            crate::settings::gateway::GatewaySettingsRefreshPlan,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "gateway_settings_refresh_unavailable.json",
            crate::settings::gateway::GatewaySettingsRefreshUnavailable,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "gateway_settings_update_plan.json",
            crate::settings::gateway::GatewaySettingsUpdatePlan,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "gateway_status_endpoint.json",
            crate::state::reducers::GatewayStatusEndpoint,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_status_level.json",
            crate::state::client_state::GatewayStatusLevel,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_status_message.json",
            crate::state::reducers::GatewayStatusMessage,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_status_projection.json",
            crate::state::reducers::GatewayStatusProjection,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_status_text_update.json",
            crate::state::reducers::GatewayStatusTextUpdate,
            Domain::Connection,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "gateway_ws_event.json",
            crate::transport::ws::GatewayWsEvent,
            Domain::Connection,
            Kind::Event,
            Stability::Provisional
        ),
        contract_type!(
            "mcp_audit_action.json",
            crate::mcp::presentation::McpAuditAction,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_audit_decision.json",
            crate::mcp::presentation::McpAuditDecision,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_audit_details_summary.json",
            crate::mcp::presentation::McpAuditDetailsSummary,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_audit_row.json",
            crate::mcp::presentation::McpAuditRow,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_capability_count.json",
            crate::mcp::presentation::McpCapabilityCount,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_capability_kind.json",
            crate::mcp::presentation::McpCapabilityKind,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_config_validation_error.json",
            crate::mcp::actions::McpConfigValidationError,
            Domain::Mcp,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "mcp_detail_meta_kind.json",
            crate::mcp::presentation::McpDetailMetaKind,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_detail_meta_row.json",
            crate::mcp::presentation::McpDetailMetaRow,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_detail_value.json",
            crate::mcp::presentation::McpDetailValue,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_install_field_error.json",
            crate::mcp::actions::McpInstallFieldError,
            Domain::Mcp,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "mcp_install_field_issue.json",
            crate::mcp::actions::McpInstallFieldIssue,
            Domain::Mcp,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "mcp_json_value_preview.json",
            crate::mcp::presentation::McpJsonValuePreview,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_list_state.json",
            crate::mcp::list::McpListState,
            Domain::Mcp,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "mcp_presentation_tone.json",
            crate::mcp::presentation::McpPresentationTone,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_scope_label.json",
            crate::mcp::presentation::McpScopeLabel,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_source_label.json",
            crate::mcp::presentation::McpSourceLabel,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_status_label.json",
            crate::mcp::presentation::McpStatusLabel,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_timeline_metadata.json",
            crate::timeline::labels::McpTimelineMetadata,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_transport_presentation.json",
            crate::mcp::presentation::McpTransportPresentation,
            Domain::Mcp,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "memory_model_setting.json",
            crate::settings::memory::MemoryModelSetting,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "memory_setting_toggle.json",
            crate::settings::memory::MemorySettingToggle,
            Domain::Settings,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "mcp_capability_selection_toggle.json",
            crate::composer::capabilities::McpCapabilitySelectionToggle,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "mcp_capability_unavailable_reason.json",
            crate::composer::capabilities::McpCapabilityUnavailableReason,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "model_provider_selection_update.json",
            crate::composer::model_selection::ModelProviderSelectionUpdate,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "model_selector_selection.json",
            crate::composer::model_selection::ModelSelectorSelection,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "parsed_user_attachment.json",
            crate::timeline::labels::ParsedUserAttachment,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "parsed_user_attachment_kind.json",
            crate::timeline::labels::ParsedUserAttachmentKind,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "prepared_composer_attachment.json",
            crate::composer::turn_prepare::PreparedComposerAttachment,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "prepare_composer_turn_request.json",
            crate::composer::turn_prepare::PrepareComposerTurnRequest,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "prepare_voice_composer_snapshot_request.json",
            crate::composer::turn_prepare::PrepareVoiceComposerSnapshotRequest,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "prepared_composer_turn.json",
            crate::composer::turn_prepare::PreparedComposerTurn,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "prepared_voice_composer_snapshot.json",
            crate::composer::turn_prepare::PreparedVoiceComposerSnapshot,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "voice_composer_snapshot_discard_reduction.json",
            crate::composer::turn_prepare::VoiceComposerSnapshotDiscardReduction,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "voice_composer_lock_state.json",
            crate::composer::turn_prepare::VoiceComposerLockState,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "voice_finalize_response_reduction.json",
            crate::voice::VoiceFinalizeResponseReduction,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "voice_finalize_ui_action.json",
            crate::voice::VoiceFinalizeUiAction,
            Domain::Composer,
            Kind::ActionState,
            Stability::Provisional
        ),
        contract_type!(
            "voice_session_result_reduction.json",
            crate::voice::VoiceSessionResultReduction,
            Domain::Composer,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_api_key_action_unavailable.json",
            crate::providers::actions::ProviderApiKeyActionUnavailable,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "provider_delete_api_key_action_request.json",
            crate::providers::actions::ProviderDeleteApiKeyActionRequest,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_delete_api_key_plan.json",
            crate::providers::actions::ProviderDeleteApiKeyPlan,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_filter.json",
            crate::providers::selectors::ProviderFilter,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "cli_runtime_provider_draft.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraft,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_provider_draft_field.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraftField,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_provider_draft_mode.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderDraftMode,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_provider_settings_plan.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderSettingsPlan,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "cli_runtime_provider_settings_rejection.json",
            crate::providers::cli_runtime_settings::CLIRuntimeProviderSettingsRejection,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "cli_runtime_provider_diagnostics_bundle.json",
            crate::providers::diagnostics::CLIRuntimeProviderDiagnosticsBundle,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "provider_model_display_key.json",
            crate::providers::presentation::ProviderModelDisplayKey,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "provider_model_display_resolution.json",
            crate::providers::presentation::ProviderModelDisplayResolution,
            Domain::Providers,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "reasoning_effort_row.json",
            crate::providers::presentation::ReasoningEffortRow,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "reasoning_effort_rows_request.json",
            crate::providers::presentation::ReasoningEffortRowsRequest,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "reasoning_effort_rows_response.json",
            crate::providers::presentation::ReasoningEffortRowsResponse,
            Domain::Providers,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "provider_list_models_params.json",
            pioneer_protocol::ProviderListModelsParams,
            Domain::Providers,
            Kind::Command,
            Stability::Stable
        ),
        contract_type!(
            "provider_list_models_response.json",
            pioneer_protocol::ProviderListModelsResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "provider_list_params.json",
            pioneer_protocol::ProviderListParams,
            Domain::Providers,
            Kind::Command,
            Stability::Stable
        ),
        contract_type!(
            "provider_list_refresh_plan.json",
            crate::providers::list::ProviderListRefreshPlan,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_list_refresh_request.json",
            crate::providers::list::ProviderListRefreshRequest,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_list_refresh_unavailable.json",
            crate::providers::list::ProviderListRefreshUnavailable,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "provider_list_response.json",
            pioneer_protocol::ProviderListResponse,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "provider_model_info.json",
            pioneer_protocol::ProviderModelInfo,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "provider_model_reasoning_capabilities.json",
            pioneer_protocol::ProviderModelReasoningCapabilities,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "reasoning_capability_source.json",
            pioneer_protocol::ReasoningCapabilitySource,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "runtime_account_snapshot.json",
            pioneer_protocol::RuntimeAccountSnapshot,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_capabilities.json",
            pioneer_protocol::RuntimeCapabilities,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_diagnostic.json",
            pioneer_protocol::RuntimeDiagnostic,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_diagnostic_level.json",
            pioneer_protocol::RuntimeDiagnosticLevel,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_model_info.json",
            pioneer_protocol::RuntimeModelInfo,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_app_info.json",
            pioneer_protocol::RuntimeAppInfo,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_status.json",
            pioneer_protocol::RuntimeStatus,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "runtime_summary.json",
            pioneer_protocol::RuntimeSummary,
            Domain::Providers,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "provider_summary.json",
            pioneer_protocol::ProviderSummary,
            Domain::Providers,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "provider_set_api_key_action_request.json",
            crate::providers::actions::ProviderSetApiKeyActionRequest,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "provider_set_api_key_plan.json",
            crate::providers::actions::ProviderSetApiKeyPlan,
            Domain::Providers,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "reconciled_skills_snapshot.json",
            crate::skills::catalog::ReconciledSkillsSnapshot,
            Domain::Skills,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "remote_gateway_validation.json",
            crate::gateway::setup::RemoteGatewayValidation,
            Domain::Connection,
            Kind::ActionState,
            Stability::Provisional
        ),
        contract_type!(
            "delete_remote_gateway_registry_plan.json",
            crate::gateway::setup::DeleteRemoteGatewayRegistryPlan,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "gateway_auth_token_update.json",
            crate::gateway::setup::GatewayAuthTokenUpdate,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "update_remote_gateway_registry_plan.json",
            crate::gateway::setup::UpdateRemoteGatewayRegistryPlan,
            Domain::Connection,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "selectable_mcp_capability.json",
            crate::composer::capabilities::SelectableMcpCapability,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "selectable_skill_capability.json",
            crate::composer::capabilities::SelectableSkillCapability,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_audit_action.json",
            crate::skills::presentation::SkillAuditAction,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_audit_decision.json",
            crate::skills::presentation::SkillAuditDecision,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_audit_details_summary.json",
            crate::skills::presentation::SkillAuditDetailsSummary,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_audit_row.json",
            crate::skills::presentation::SkillAuditRow,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_capability_unavailable_reason.json",
            crate::composer::capabilities::SkillCapabilityUnavailableReason,
            Domain::Composer,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_catalog_state.json",
            crate::skills::catalog::SkillCatalogState,
            Domain::Skills,
            Kind::Snapshot,
            Stability::Provisional
        ),
        contract_type!(
            "skill_dependency_card.json",
            crate::skills::presentation::SkillDependencyCard,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_dependency_kind.json",
            crate::skills::presentation::SkillDependencyKind,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_dependency_status.json",
            crate::skills::presentation::SkillDependencyStatus,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_detail_diagnostics.json",
            crate::skills::presentation::SkillDetailDiagnostics,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_diagnostics_table_cell.json",
            crate::skills::presentation::SkillDiagnosticsTableCell,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_diagnostics_table_row.json",
            crate::skills::presentation::SkillDiagnosticsTableRow,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_diagnostics_tone.json",
            crate::skills::presentation::SkillDiagnosticsTone,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_json_value_preview.json",
            crate::skills::presentation::SkillJsonValuePreview,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_security_card.json",
            crate::skills::presentation::SkillSecurityCard,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_security_severity.json",
            crate::skills::presentation::SkillSecuritySeverity,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_slug_presentation.json",
            crate::skills::presentation::SkillSlugPresentation,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_source_kind.json",
            crate::skills::presentation::SkillSourceKind,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_status.json",
            crate::skills::presentation::SkillStatus,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_summary_presentation.json",
            crate::skills::presentation::SkillSummaryPresentation,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_trust_gate_card.json",
            crate::skills::presentation::SkillTrustGateCard,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_trust_gate_decision.json",
            crate::skills::presentation::SkillTrustGateDecision,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_trust_gate_tool_kind.json",
            crate::skills::presentation::SkillTrustGateToolKind,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skill_trust_level.json",
            crate::skills::presentation::SkillTrustLevel,
            Domain::Skills,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "skills_catalog_snapshot.json",
            crate::skills::catalog::SkillsCatalogSnapshot,
            Domain::Skills,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "skills_catalog_split.json",
            crate::skills::catalog::SkillsCatalogSplit,
            Domain::Skills,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "system_event_detail_row.json",
            crate::timeline::labels::SystemEventDetailRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "system_event_presentation.json",
            crate::timeline::labels::SystemEventPresentation,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "task_review_action.json",
            crate::tasks::review::TaskReviewAction,
            Domain::Tasks,
            Kind::ActionState,
            Stability::Stable
        ),
        contract_type!(
            "task_review_action_state.json",
            crate::tasks::review::TaskReviewActionState,
            Domain::Tasks,
            Kind::ActionState,
            Stability::Stable
        ),
        contract_type!(
            "task_review_plan_error.json",
            crate::tasks::review::TaskReviewPlanError,
            Domain::Tasks,
            Kind::ActionPlan,
            Stability::Stable
        ),
        contract_type!(
            "task_wait_review_display.json",
            crate::timeline::labels::TaskWaitReviewDisplay,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "task_wait_review_display_item.json",
            crate::timeline::labels::TaskWaitReviewDisplayItem,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "thread_artifact_cache_entry.json",
            crate::artifacts::state::ThreadArtifactCacheEntry,
            Domain::Artifacts,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "thread_artifact_filter.json",
            crate::artifacts::state::ThreadArtifactFilter,
            Domain::Artifacts,
            Kind::SelectorDto,
            Stability::Stable
        ),
        contract_type!(
            "artifact_binding_target_kind.json",
            crate::artifacts::presentation::ArtifactBindingTargetKind,
            Domain::Artifacts,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "artifact_binding_target_part.json",
            crate::artifacts::presentation::ArtifactBindingTargetPart,
            Domain::Artifacts,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "thread_list_snapshot.json",
            crate::state::snapshot::ThreadListSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "thread_tree_refresh_failure_reduction.json",
            crate::threads::tree::ThreadTreeRefreshFailureReduction,
            Domain::Root,
            Kind::ActionState,
            Stability::Provisional
        ),
        contract_type!(
            "thread_tree_refresh_success_reduction.json",
            crate::threads::tree::ThreadTreeRefreshSuccessReduction,
            Domain::Root,
            Kind::ActionState,
            Stability::Provisional
        ),
        contract_type!(
            "timeline_coalesced_tools_kind.json",
            crate::timeline::rows::TimelineCoalescedToolsKind,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "timeline_coalesced_tools_row.json",
            crate::timeline::rows::TimelineCoalescedToolsRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "timeline_final_status.json",
            crate::timeline::labels::TimelineFinalStatus,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "timeline_final_status_kind.json",
            crate::timeline::labels::TimelineFinalStatusKind,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "timeline_row.json",
            crate::timeline::rows::TimelineRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "timeline_row_kind.json",
            crate::timeline::rows::TimelineRowKind,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "turn_cli_runtime_options.json",
            pioneer_protocol::TurnCLIRuntimeOptions,
            Domain::Providers,
            Kind::Command,
            Stability::Provisional
        ),
        contract_type!(
            "turn_reasoning_selection.json",
            pioneer_protocol::TurnReasoningSelection,
            Domain::Composer,
            Kind::Command,
            Stability::Stable
        ),
        contract_type!(
            "turn_work_group_row.json",
            crate::timeline::rows::TurnWorkGroupRow,
            Domain::Timeline,
            Kind::PresentationDto,
            Stability::Stable
        ),
        contract_type!(
            "workspace_snapshot.json",
            crate::state::snapshot::WorkspaceSnapshot,
            Domain::Root,
            Kind::Snapshot,
            Stability::Stable
        ),
        contract_type!(
            "workspace_bootstrap_request.json",
            crate::workspaces::bootstrap::WorkspaceBootstrapRequest,
            Domain::Root,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "workspace_bootstrap_success_reduction.json",
            crate::workspaces::actions::WorkspaceBootstrapSuccessReduction,
            Domain::Root,
            Kind::ActionPlan,
            Stability::Provisional
        ),
        contract_type!(
            "workspace_selection_reduction.json",
            crate::workspaces::actions::WorkspaceSelectionReduction,
            Domain::Root,
            Kind::ActionPlan,
            Stability::Provisional
        ),
    ];

    contracts.sort_by(|left, right| left.file_name.cmp(right.file_name));
    contracts
}

pub fn client_schema_internal_exclusions() -> Vec<ClientSchemaInternalExclusion> {
    vec![
        internal_exclusion!(
            crate::state::client_state::ClientState,
            "aggregate mutable Rust state, not a shell snapshot DTO"
        ),
        internal_exclusion!(
            crate::state::client_state::ThreadsState,
            "aggregate mutable Rust state, not a shell snapshot DTO"
        ),
        internal_exclusion!(
            crate::state::client_state::WorkspacesState,
            "aggregate mutable Rust state, not a shell snapshot DTO"
        ),
        internal_exclusion!(
            crate::state::client_state::GatewayClientState,
            "aggregate mutable Rust state, not a shell snapshot DTO"
        ),
        internal_exclusion!(
            crate::state::client_state::SettingsState,
            "aggregate mutable Rust state, not a shell snapshot DTO"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewaySwitchCleanupPlan,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayStatusInput,
            "selector input, not a shell contract"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayConnectionEvent,
            "connection reducer input, not a shell event contract"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewaySettingsConnectionUpdate,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayConnectionReduction,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayOperationSuccessInfo,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayOperationFinishOutcome,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::state::reducers::GatewayOperationFinishReduction,
            "reducer implementation detail"
        ),
        internal_exclusion!(
            crate::notifications::router::ThreadStartedReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::TurnLifecycleReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ConversationEventReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ThreadClosedReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ThreadUpdatedReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::WorkspaceRefreshReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::SkillsRefreshReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ThreadArtifactsRefreshReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ArtifactThreadRefreshReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::notifications::router::ArtifactDeletedRefreshReduction,
            "notification reducer output consumed inside Rust state mutation"
        ),
        internal_exclusion!(
            crate::conversation::reducer::ConversationProjector,
            "projector implementation detail"
        ),
        internal_exclusion!(
            crate::conversation::reducer::ConversationViewState,
            "conversation read model is projected to shell-facing timeline rows"
        ),
        internal_exclusion!(
            crate::conversation::reducer::TurnView,
            "conversation read model is projected to shell-facing timeline rows"
        ),
        internal_exclusion!(
            crate::conversation::reducer::ItemView,
            "conversation read model is projected to shell-facing timeline rows"
        ),
        internal_exclusion!(
            crate::conversation::reducer::TimelineEntry,
            "conversation read model is projected to shell-facing timeline rows"
        ),
        internal_exclusion!(
            crate::threads::coordinator::ThreadCoordinator,
            "mutable per-thread coordinator state"
        ),
        internal_exclusion!(
            crate::threads::start::ThreadStartCoordinator,
            "workflow coordinator state"
        ),
        internal_exclusion!(
            crate::threads::resume::ThreadResumeCoordinator,
            "workflow coordinator state"
        ),
        internal_exclusion!(
            crate::conversation::state_machine::TurnStateMachine,
            "state machine implementation detail"
        ),
        internal_exclusion!(
            crate::artifacts::actions::ArtifactLocalFile,
            "native filesystem handle used by Rust artifact file actions"
        ),
        internal_exclusion!(
            crate::artifacts::actions::ThreadArtifactActionState,
            "mutable per-thread artifact action state"
        ),
        internal_exclusion!(
            crate::artifacts::actions::ArtifactCachedDownload,
            "native cache file descriptor used behind platform file traits"
        ),
        internal_exclusion!(
            crate::artifacts::preview::ArtifactPreviewImagePaths,
            "native preview cache paths, not a shell DTO"
        ),
        internal_exclusion!(
            crate::artifacts::preview::ArtifactPreviewReadData,
            "binary preview read buffer used inside Rust cache orchestration"
        ),
        internal_exclusion!(
            crate::artifacts::preview::ArtifactPreviewVariantTarget,
            "native image rendering target used behind platform preview traits"
        ),
        internal_exclusion!(
            crate::artifacts::preview::ThreadArtifactPreviewState,
            "mutable per-thread preview cache state"
        ),
        internal_exclusion!(
            crate::mcp::list::McpSnapshotApplication,
            "snapshot reconciliation output consumed inside Rust state mutation"
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn client_contract_files_are_unique_and_sorted() {
        let contracts = client_contract_types();
        assert!(!contracts.is_empty());

        let file_names = contracts
            .iter()
            .map(|contract| contract.file_name)
            .collect::<Vec<_>>();
        let mut sorted = file_names.clone();
        sorted.sort_unstable();
        sorted.dedup();

        assert_eq!(file_names, sorted);
    }

    #[test]
    fn client_contract_boundary_covers_phase_28_domains() {
        let domains = client_contract_types()
            .into_iter()
            .map(|contract| contract.domain)
            .collect::<BTreeSet<_>>();

        for expected in [
            ClientContractDomain::Root,
            ClientContractDomain::Connection,
            ClientContractDomain::Timeline,
            ClientContractDomain::Composer,
            ClientContractDomain::Artifacts,
            ClientContractDomain::Providers,
            ClientContractDomain::Skills,
            ClientContractDomain::Mcp,
            ClientContractDomain::Settings,
            ClientContractDomain::Tasks,
        ] {
            assert!(domains.contains(&expected), "missing domain {expected:?}");
        }
    }

    #[test]
    fn client_contract_boundary_exports_phase35_cli_runtime_contracts() {
        let files = client_contract_types()
            .into_iter()
            .map(|contract| contract.file_name)
            .collect::<BTreeSet<_>>();

        for expected in [
            "agent_execution_backend.json",
            "cli_agent_runtime_kind.json",
            "cli_agent_runtime_sandbox_policy.json",
            "turn_cli_runtime_options.json",
            "runtime_summary.json",
            "runtime_status.json",
            "runtime_model_info.json",
            "runtime_app_info.json",
            "runtime_capabilities.json",
            "runtime_account_snapshot.json",
            "runtime_diagnostic.json",
            "runtime_diagnostic_level.json",
            "cli_runtime_list_params.json",
            "cli_runtime_list_response.json",
            "cli_runtime_get_params.json",
            "cli_runtime_get_response.json",
            "cli_runtime_status_params.json",
            "cli_runtime_status_response.json",
            "cli_runtime_refresh_params.json",
            "cli_runtime_refresh_response.json",
            "cli_runtime_list_models_params.json",
            "cli_runtime_list_models_response.json",
            "cli_runtime_thread_binding_get_params.json",
            "cli_runtime_thread_binding_get_response.json",
            "cli_runtime_thread_binding.json",
            "cli_runtime_thread_compact_params.json",
            "cli_runtime_thread_compact_response.json",
            "cli_runtime_thread_fork_params.json",
            "cli_runtime_thread_fork_response.json",
            "cli_runtime_turn_steer_params.json",
            "cli_runtime_turn_steer_response.json",
            "cli_runtime_review_delivery.json",
            "cli_runtime_review_target.json",
            "cli_runtime_review_start_params.json",
            "cli_runtime_review_start_response.json",
            "cli_runtime_login_start_type.json",
            "cli_runtime_login_start_params.json",
            "cli_runtime_login_start_response.json",
            "cli_runtime_login_cancel_params.json",
            "cli_runtime_login_cancel_response.json",
            "cli_runtime_pending_request.json",
            "cli_runtime_request_kind.json",
            "cli_runtime_request_resolution.json",
            "cli_runtime_status_changed_notification.json",
            "cli_runtime_account_updated_notification.json",
            "cli_runtime_request_opened_notification.json",
            "cli_runtime_request_resolved_notification.json",
            "cli_runtime_apps_changed_notification.json",
        ] {
            assert!(files.contains(expected), "missing contract {expected}");
        }
    }

    #[test]
    fn client_contract_boundary_excludes_internal_reducer_types() {
        let public_types = client_contract_types()
            .into_iter()
            .map(|contract| contract.rust_type)
            .collect::<BTreeSet<_>>();

        for exclusion in client_schema_internal_exclusions() {
            assert!(
                !public_types.contains(exclusion.rust_type),
                "internal type is public: {}",
                exclusion.rust_type
            );
        }
    }
}
