[package]
name = "pioneer-migration"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
sea-orm-migration = { workspace = true, features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
pioneer-entity.workspace = true
pioneer-observability.workspace = true
pioneer-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
pioneer-sqlite.workspace = true
