[package]
name = "pioneer-tasks"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
pioneer-crud.workspace = true
pioneer-protocol.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
pioneer-migration.workspace = true
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
